// Generated by scripts/build.mjs from tokens/*.json. Do not edit; change the Figma variables and export.

import SwiftUI
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

/// Design tokens. Sizes are points (1pt = 1px = 1/16rem); colors follow the system appearance.
public enum SoftwareTokens {
    public enum Accordion {
        /// accordion/border/radius/default
        public static let borderRadiusDefault: CGFloat = 8

        /// accordion/border/width/default
        public static let borderWidthDefault: CGFloat = 1

        /// accordion/color/background/default
        public static let colorBackgroundDefault = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// accordion/color/border/default
        public static let colorBorderDefault = SwiftUI.Color(light: 0xC5C6C9FF, dark: 0x42454EFF)

        /// accordion/color/border/hover
        public static let colorBorderHover = SwiftUI.Color(light: 0x6F7078FF, dark: 0x6F7078FF)

        /// accordion/color/content/active
        public static let colorContentActive = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// accordion/color/content/default
        public static let colorContentDefault = SwiftUI.Color(light: 0x6F7078FF, dark: 0x8C8F9BFF)

        /// accordion/color/content/disabled
        public static let colorContentDisabled = SwiftUI.Color(light: 0x61646BFF, dark: 0x61646BFF)

        /// accordion/color/content/focus
        public static let colorContentFocus = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// accordion/color/content/hover
        public static let colorContentHover = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// accordion/spacing/gap
        public static let spacingGap: CGFloat = 16

        /// accordion/spacing/padding-x
        public static let spacingPaddingX: CGFloat = 24

        /// accordion/spacing/padding-y
        public static let spacingPaddingY: CGFloat = 16
    }

    public enum Border {
        /// border/radius/lg
        public static let radiusLg: CGFloat = 24

        /// border/radius/md
        public static let radiusMd: CGFloat = 16

        /// border/radius/none
        public static let radiusNone: CGFloat = 0

        /// border/radius/round
        public static let radiusRound: CGFloat = 9999

        /// border/radius/sm
        public static let radiusSm: CGFloat = 8

        /// border/radius/xlg
        public static let radiusXlg: CGFloat = 48

        /// border/radius/xsm
        public static let radiusXsm: CGFloat = 4

        /// border/radius/xxsm
        public static let radiusXxsm: CGFloat = 2

        /// border/width/default
        public static let widthDefault: CGFloat = 1

        /// border/width/lg
        public static let widthLg: CGFloat = 8

        /// border/width/md
        public static let widthMd: CGFloat = 4

        /// border/width/sm
        public static let widthSm: CGFloat = 2
    }

    public enum Button {
        /// button/border/radius/default
        public static let borderRadiusDefault: CGFloat = 4

        /// button/border/radius/focus
        public static let borderRadiusFocus: CGFloat = 4

        /// button/border/radius/hover
        public static let borderRadiusHover: CGFloat = 4

        /// button/border/radius/lg
        public static let borderRadiusLg: CGFloat = 24

        /// button/border/radius/md
        public static let borderRadiusMd: CGFloat = 16

        /// button/border/radius/round
        public static let borderRadiusRound: CGFloat = 9999

        /// button/border/radius/sm
        public static let borderRadiusSm: CGFloat = 8

        /// button/border/radius/xlg
        public static let borderRadiusXlg: CGFloat = 48

        /// button/border/width/default
        public static let borderWidthDefault: CGFloat = 1

        /// button/border/width/hover
        public static let borderWidthHover: CGFloat = 1

        /// button/color/danger/background/default
        public static let colorDangerBackgroundDefault = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// button/color/danger/background/focus
        public static let colorDangerBackgroundFocus = SwiftUI.Color(light: 0xFCEAEFFF, dark: 0x390E0EFF)

        /// button/color/danger/background/hover
        public static let colorDangerBackgroundHover = SwiftUI.Color(light: 0xFCEAEFFF, dark: 0x390E0EFF)

        /// button/color/danger/border/default
        public static let colorDangerBorderDefault = SwiftUI.Color(light: 0x8D2121FF, dark: 0xDD7C88FF)

        /// button/color/danger/border/focus
        public static let colorDangerBorderFocus = SwiftUI.Color(light: 0x8D2121FF, dark: 0xDD7C88FF)

        /// button/color/danger/border/hover
        public static let colorDangerBorderHover = SwiftUI.Color(light: 0xB82F30FF, dark: 0xEFA2B2FF)

        /// button/color/danger/content/default
        public static let colorDangerContentDefault = SwiftUI.Color(light: 0xB82F30FF, dark: 0xEFA2B2FF)

        /// button/color/danger/content/focus
        public static let colorDangerContentFocus = SwiftUI.Color(light: 0xB82F30FF, dark: 0xEFA2B2FF)

        /// button/color/danger/content/hover
        public static let colorDangerContentHover = SwiftUI.Color(light: 0xB82F30FF, dark: 0xEFA2B2FF)

        /// button/color/disabled/background/default
        public static let colorDisabledBackgroundDefault = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0x161925FF)

        /// button/color/disabled/border/default
        public static let colorDisabledBorderDefault = SwiftUI.Color(light: 0x6F7078FF, dark: 0x42454EFF)

        /// button/color/disabled/content/default
        public static let colorDisabledContentDefault = SwiftUI.Color(light: 0x61646BFF, dark: 0x61646BFF)

        /// button/color/ghost/background/default
        public static let colorGhostBackgroundDefault = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// button/color/ghost/background/disabled
        public static let colorGhostBackgroundDisabled = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0x161925FF)

        /// button/color/ghost/background/focus
        public static let colorGhostBackgroundFocus = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// button/color/ghost/background/hover
        public static let colorGhostBackgroundHover = SwiftUI.Color(light: 0xF7F7F7FF, dark: 0x161925FF)

        /// button/color/ghost/border/default
        public static let colorGhostBorderDefault = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// button/color/ghost/border/disabled
        public static let colorGhostBorderDisabled = SwiftUI.Color(light: 0x6F7078FF, dark: 0x42454EFF)

        /// button/color/ghost/border/focus
        public static let colorGhostBorderFocus = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/ghost/border/hover
        public static let colorGhostBorderHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/ghost/content/default
        public static let colorGhostContentDefault = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// button/color/ghost/content/disabled
        public static let colorGhostContentDisabled = SwiftUI.Color(light: 0x61646BFF, dark: 0x61646BFF)

        /// button/color/ghost/content/focus
        public static let colorGhostContentFocus = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// button/color/ghost/content/hover
        public static let colorGhostContentHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/outline/background/default
        public static let colorOutlineBackgroundDefault = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// button/color/outline/background/disabled
        public static let colorOutlineBackgroundDisabled = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0x161925FF)

        /// button/color/outline/background/focus
        public static let colorOutlineBackgroundFocus = SwiftUI.Color(light: 0xF7F7F7FF, dark: 0x161925FF)

        /// button/color/outline/background/hover
        public static let colorOutlineBackgroundHover = SwiftUI.Color(light: 0xF7F7F7FF, dark: 0x161925FF)

        /// button/color/outline/border/default
        public static let colorOutlineBorderDefault = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// button/color/outline/border/disabled
        public static let colorOutlineBorderDisabled = SwiftUI.Color(light: 0x6F7078FF, dark: 0x42454EFF)

        /// button/color/outline/border/focus
        public static let colorOutlineBorderFocus = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/outline/border/hover
        public static let colorOutlineBorderHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/outline/content/default
        public static let colorOutlineContentDefault = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// button/color/outline/content/disabled
        public static let colorOutlineContentDisabled = SwiftUI.Color(light: 0x61646BFF, dark: 0x61646BFF)

        /// button/color/outline/content/focus
        public static let colorOutlineContentFocus = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/outline/content/hover
        public static let colorOutlineContentHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/primary/background/default
        public static let colorPrimaryBackgroundDefault = SwiftUI.Color(light: 0x254EDBFF, dark: 0x254EDBFF)

        /// button/color/primary/background/disabled
        public static let colorPrimaryBackgroundDisabled = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0x161925FF)

        /// button/color/primary/background/focus
        public static let colorPrimaryBackgroundFocus = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x2B59EBFF)

        /// button/color/primary/background/hover
        public static let colorPrimaryBackgroundHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x2B59EBFF)

        /// button/color/primary/border/default
        public static let colorPrimaryBorderDefault = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// button/color/primary/border/disabled
        public static let colorPrimaryBorderDisabled = SwiftUI.Color(light: 0x6F7078FF, dark: 0x42454EFF)

        /// button/color/primary/border/focus
        public static let colorPrimaryBorderFocus = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/primary/border/hover
        public static let colorPrimaryBorderHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// button/color/primary/content/default
        public static let colorPrimaryContentDefault = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// button/color/primary/content/disabled
        public static let colorPrimaryContentDisabled = SwiftUI.Color(light: 0x61646BFF, dark: 0x61646BFF)

        /// button/color/primary/content/focus
        public static let colorPrimaryContentFocus = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// button/color/primary/content/hover
        public static let colorPrimaryContentHover = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// button/focus-ring/inner-shadow/blur
        public static let focusRingInnerShadowBlur: CGFloat = 0

        /// button/focus-ring/inner-shadow/inner-shadow
        public static let focusRingInnerShadowInnerShadow = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// button/focus-ring/inner-shadow/spread
        public static let focusRingInnerShadowSpread: CGFloat = 2

        /// button/focus-ring/inner-shadow/x
        public static let focusRingInnerShadowX: CGFloat = 0

        /// button/focus-ring/inner-shadow/y
        public static let focusRingInnerShadowY: CGFloat = 0

        /// button/focus-ring/outer-shadow/blur
        public static let focusRingOuterShadowBlur: CGFloat = 0

        /// button/focus-ring/outer-shadow/outer-shadow
        public static let focusRingOuterShadowOuterShadow = SwiftUI.Color(light: 0x254EDBFF, dark: 0x254EDBFF)

        /// button/focus-ring/outer-shadow/spread
        public static let focusRingOuterShadowSpread: CGFloat = 4

        /// button/focus-ring/outer-shadow/x
        public static let focusRingOuterShadowX: CGFloat = 0

        /// button/focus-ring/outer-shadow/y
        public static let focusRingOuterShadowY: CGFloat = 0

        /// button/spacing/default/gap
        public static let spacingDefaultGap: CGFloat = 8

        /// button/spacing/default/min-height
        public static let spacingDefaultMinHeight: CGFloat = 48

        /// button/spacing/default/padding-x
        public static let spacingDefaultPaddingX: CGFloat = 16

        /// button/spacing/default/padding-y
        public static let spacingDefaultPaddingY: CGFloat = 8

        /// button/spacing/ghost/padding-x
        public static let spacingGhostPaddingX: CGFloat = 0

        /// button/spacing/groups/gap
        public static let spacingGroupsGap: CGFloat = 16

        /// button/spacing/groups/padding-y
        public static let spacingGroupsPaddingY: CGFloat = 16

        /// button/typography/font-size
        public static let typographyFontSize: CGFloat = 14

        /// button/typography/font-weight
        public static let typographyFontWeight = SwiftUI.Font.Weight.medium

        /// button/typography/letter-spacing
        public static let typographyLetterSpacing: CGFloat = 0.5

        /// button/typography/line-height
        public static let typographyLineHeight: CGFloat = 20

        /// button/typography/text-transform
        public static let typographyTextTransform = "capitalize"
    }

    public enum Color {
        /// color/background/brand
        public static let backgroundBrand = SwiftUI.Color(light: 0x254EDBFF, dark: 0x254EDBFF)

        /// color/background/brand-hover
        public static let backgroundBrandHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x2B59EBFF)

        /// color/background/default
        public static let backgroundDefault = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// color/background/disabled
        public static let backgroundDisabled = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0x161925FF)

        /// color/background/knockout
        public static let backgroundKnockout = SwiftUI.Color(light: 0x252525FF, dark: 0x42454EFF)

        /// color/background/knockout-hover
        public static let backgroundKnockoutHover = SwiftUI.Color(light: 0x000000FF, dark: 0x000000FF)

        /// color/background/knockout-translucent
        public static let backgroundKnockoutTranslucent = SwiftUI.Color(light: 0x000000CC, dark: 0x000000CC)

        /// color/background/selected
        public static let backgroundSelected = SwiftUI.Color(light: 0xAAD6EBFF, dark: 0x13293DFF)

        /// color/background/subtle
        public static let backgroundSubtle = SwiftUI.Color(light: 0xF7F7F7FF, dark: 0x161925FF)

        /// color/background/subtle-hover
        public static let backgroundSubtleHover = SwiftUI.Color(light: 0xD9D9D9FF, dark: 0x42454EFF)

        /// color/background/utility/error
        public static let backgroundUtilityError = SwiftUI.Color(light: 0xFCEAEFFF, dark: 0x390E0EFF)

        /// color/background/utility/error-knockout
        public static let backgroundUtilityErrorKnockout = SwiftUI.Color(light: 0xB82F30FF, dark: 0xB82F30FF)

        /// color/background/utility/info
        public static let backgroundUtilityInfo = SwiftUI.Color(light: 0xECEEFCFF, dark: 0x15193FFF)

        /// color/background/utility/info-knockout
        public static let backgroundUtilityInfoKnockout = SwiftUI.Color(light: 0x4555D3FF, dark: 0x4555D3FF)

        /// color/background/utility/success
        public static let backgroundUtilitySuccess = SwiftUI.Color(light: 0xDCF3EEFF, dark: 0x03211AFF)

        /// color/background/utility/success-knockout
        public static let backgroundUtilitySuccessKnockout = SwiftUI.Color(light: 0x0B7058FF, dark: 0x0B7058FF)

        /// color/background/utility/warning
        public static let backgroundUtilityWarning = SwiftUI.Color(light: 0xF9EFBBFF, dark: 0x2C1900FF)

        /// color/background/utility/warning-knockout
        public static let backgroundUtilityWarningKnockout = SwiftUI.Color(light: 0x8A5801FF, dark: 0x8A5801FF)

        /// color/border/brand
        public static let borderBrand = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// color/border/brand-hover
        public static let borderBrandHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// color/border/default
        public static let borderDefault = SwiftUI.Color(light: 0x6F7078FF, dark: 0x6F7078FF)

        /// color/border/disabled
        public static let borderDisabled = SwiftUI.Color(light: 0x6F7078FF, dark: 0x42454EFF)

        /// color/border/focus
        public static let borderFocus = SwiftUI.Color(light: 0x254EDBFF, dark: 0x2B59EBFF)

        /// color/border/hover
        public static let borderHover = SwiftUI.Color(light: 0x436C8AFF, dark: 0x436C8AFF)

        /// color/border/knockout
        public static let borderKnockout = SwiftUI.Color(light: 0xFFFFFFCC, dark: 0xFFFFFFCC)

        /// color/border/knockout-hover
        public static let borderKnockoutHover = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)

        /// color/border/selected
        public static let borderSelected = SwiftUI.Color(light: 0x13293DFF, dark: 0x73A6C4FF)

        /// color/border/subtle
        public static let borderSubtle = SwiftUI.Color(light: 0xC5C6C9FF, dark: 0x42454EFF)

        /// color/border/subtle-hover
        public static let borderSubtleHover = SwiftUI.Color(light: 0x8C8F9BFF, dark: 0x6F7078FF)

        /// color/border/utility/error
        public static let borderUtilityError = SwiftUI.Color(light: 0x8D2121FF, dark: 0xDD7C88FF)

        /// color/border/utility/info
        public static let borderUtilityInfo = SwiftUI.Color(light: 0x34409EFF, dark: 0x8792EAFF)

        /// color/border/utility/success
        public static let borderUtilitySuccess = SwiftUI.Color(light: 0x085442FF, dark: 0x11AD86FF)

        /// color/border/utility/warning
        public static let borderUtilityWarning = SwiftUI.Color(light: 0x6D3F00FF, dark: 0xDBB305FF)

        /// color/brand/default
        public static let brandDefault = SwiftUI.Color(light: 0x254EDBFF, dark: 0x254EDBFF)

        /// color/brand/hover
        public static let brandHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x2B59EBFF)

        /// color/content/brand
        public static let contentBrand = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// color/content/brand-hover
        public static let contentBrandHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// color/content/brand-knockout
        public static let contentBrandKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/content/default
        public static let contentDefault = SwiftUI.Color(light: 0x42454EFF, dark: 0xC5C6C9FF)

        /// color/content/disabled
        public static let contentDisabled = SwiftUI.Color(light: 0x61646BFF, dark: 0x61646BFF)

        /// color/content/emphasized
        public static let contentEmphasized = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// color/content/eyebrow
        public static let contentEyebrow = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// color/content/eyebrow-knockout
        public static let contentEyebrowKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/content/headline
        public static let contentHeadline = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// color/content/headline-brand
        public static let contentHeadlineBrand = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// color/content/headline-knockout
        public static let contentHeadlineKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/content/knockout
        public static let contentKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/content/link
        public static let contentLink = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// color/content/link-hover
        public static let contentLinkHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)

        /// color/content/subtitle
        public static let contentSubtitle = SwiftUI.Color(light: 0x42454EFF, dark: 0xC5C6C9FF)

        /// color/content/subtitle-knockout
        public static let contentSubtitleKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/content/subtle
        public static let contentSubtle = SwiftUI.Color(light: 0x6F7078FF, dark: 0x8C8F9BFF)

        /// color/content/utility/error
        public static let contentUtilityError = SwiftUI.Color(light: 0xB82F30FF, dark: 0xEFA2B2FF)

        /// color/content/utility/error-knockout
        public static let contentUtilityErrorKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/content/utility/info
        public static let contentUtilityInfo = SwiftUI.Color(light: 0x4555D3FF, dark: 0xABB3F0FF)

        /// color/content/utility/info-knockout
        public static let contentUtilityInfoKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/content/utility/success
        public static let contentUtilitySuccess = SwiftUI.Color(light: 0x0B7058FF, dark: 0x5DC9AFFF)

        /// color/content/utility/success-knockout
        public static let contentUtilitySuccessKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/content/utility/warning
        public static let contentUtilityWarning = SwiftUI.Color(light: 0x8A5801FF, dark: 0xEFD242FF)

        /// color/content/utility/warning-knockout
        public static let contentUtilityWarningKnockout = SwiftUI.Color(light: 0xF3F4F4FF, dark: 0xF3F4F4FF)

        /// color/elevation/shadow
        public static let elevationShadow = SwiftUI.Color(light: 0x00000066, dark: 0x000000CC)
    }

    public enum Elevation {
        /// elevation/lg/blur
        public static let lgBlur: CGFloat = 48

        /// elevation/lg/color
        public static let lgColor = SwiftUI.Color(light: 0x00000066, dark: 0x000000CC)

        /// elevation/lg/spread
        public static let lgSpread: CGFloat = 0

        /// elevation/lg/x
        public static let lgX: CGFloat = 0

        /// elevation/lg/y
        public static let lgY: CGFloat = 24

        /// elevation/md/blur
        public static let mdBlur: CGFloat = 32

        /// elevation/md/color
        public static let mdColor = SwiftUI.Color(light: 0x00000066, dark: 0x000000CC)

        /// elevation/md/spread
        public static let mdSpread: CGFloat = 0

        /// elevation/md/x
        public static let mdX: CGFloat = 0

        /// elevation/md/y
        public static let mdY: CGFloat = 16

        /// elevation/sm/blur
        public static let smBlur: CGFloat = 16

        /// elevation/sm/color
        public static let smColor = SwiftUI.Color(light: 0x00000066, dark: 0x000000CC)

        /// elevation/sm/spread
        public static let smSpread: CGFloat = 0

        /// elevation/sm/x
        public static let smX: CGFloat = 0

        /// elevation/sm/y
        public static let smY: CGFloat = 8

        /// elevation/surface/blur
        public static let surfaceBlur: CGFloat = 2

        /// elevation/surface/color
        public static let surfaceColor = SwiftUI.Color(light: 0x00000066, dark: 0x000000CC)

        /// elevation/surface/spread
        public static let surfaceSpread: CGFloat = 0

        /// elevation/surface/x
        public static let surfaceX: CGFloat = 0

        /// elevation/surface/y
        public static let surfaceY: CGFloat = 1

        /// elevation/xlg/blur
        public static let xlgBlur: CGFloat = 96

        /// elevation/xlg/color
        public static let xlgColor = SwiftUI.Color(light: 0x00000066, dark: 0x000000CC)

        /// elevation/xlg/spread
        public static let xlgSpread: CGFloat = 0

        /// elevation/xlg/x
        public static let xlgX: CGFloat = 0

        /// elevation/xlg/y
        public static let xlgY: CGFloat = 48

        /// elevation/xsm/blur
        public static let xsmBlur: CGFloat = 8

        /// elevation/xsm/color
        public static let xsmColor = SwiftUI.Color(light: 0x00000066, dark: 0x000000CC)

        /// elevation/xsm/spread
        public static let xsmSpread: CGFloat = 0

        /// elevation/xsm/x
        public static let xsmX: CGFloat = 0

        /// elevation/xsm/y
        public static let xsmY: CGFloat = 4

        /// elevation/xxsm/blur
        public static let xxsmBlur: CGFloat = 4

        /// elevation/xxsm/color
        public static let xxsmColor = SwiftUI.Color(light: 0x00000066, dark: 0x000000CC)

        /// elevation/xxsm/spread
        public static let xxsmSpread: CGFloat = 0

        /// elevation/xxsm/x
        public static let xxsmX: CGFloat = 0

        /// elevation/xxsm/y
        public static let xxsmY: CGFloat = 2
    }

    public enum Field {
        /// field/border/radius/default
        public static let borderRadiusDefault: CGFloat = 4

        /// field/border/radius/read-only
        public static let borderRadiusReadOnly: CGFloat = 0

        /// field/border/radius/search
        public static let borderRadiusSearch: CGFloat = 9999

        /// field/border/width/default
        public static let borderWidthDefault: CGFloat = 1

        /// field/color/background/active
        public static let colorBackgroundActive = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// field/color/background/default
        public static let colorBackgroundDefault = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// field/color/background/disabled
        public static let colorBackgroundDisabled = SwiftUI.Color(light: 0xF7F7F7FF, dark: 0x161925FF)

        /// field/color/background/focus
        public static let colorBackgroundFocus = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// field/color/background/hover
        public static let colorBackgroundHover = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// field/color/background/selected
        public static let colorBackgroundSelected = SwiftUI.Color(light: 0xAAD6EBFF, dark: 0x13293DFF)

        /// field/color/border/default
        public static let colorBorderDefault = SwiftUI.Color(light: 0x6F7078FF, dark: 0x6F7078FF)

        /// field/color/border/disabled
        public static let colorBorderDisabled = SwiftUI.Color(light: 0x6F7078FF, dark: 0x42454EFF)

        /// field/color/border/error
        public static let colorBorderError = SwiftUI.Color(light: 0x8D2121FF, dark: 0xDD7C88FF)

        /// field/color/border/focus
        public static let colorBorderFocus = SwiftUI.Color(light: 0x254EDBFF, dark: 0x2B59EBFF)

        /// field/color/border/hover
        public static let colorBorderHover = SwiftUI.Color(light: 0x436C8AFF, dark: 0x436C8AFF)

        /// field/color/border/selected
        public static let colorBorderSelected = SwiftUI.Color(light: 0x13293DFF, dark: 0x73A6C4FF)

        /// field/color/border/success
        public static let colorBorderSuccess = SwiftUI.Color(light: 0x085442FF, dark: 0x11AD86FF)

        /// field/color/content/default
        public static let colorContentDefault = SwiftUI.Color(light: 0x6F7078FF, dark: 0x8C8F9BFF)

        /// field/color/content/disabled
        public static let colorContentDisabled = SwiftUI.Color(light: 0x61646BFF, dark: 0x61646BFF)

        /// field/color/content/error
        public static let colorContentError = SwiftUI.Color(light: 0xB82F30FF, dark: 0xEFA2B2FF)

        /// field/color/content/focus
        public static let colorContentFocus = SwiftUI.Color(light: 0x42454EFF, dark: 0xC5C6C9FF)

        /// field/color/content/hover
        public static let colorContentHover = SwiftUI.Color(light: 0x42454EFF, dark: 0xC5C6C9FF)

        /// field/color/content/label
        public static let colorContentLabel = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// field/color/content/selected
        public static let colorContentSelected = SwiftUI.Color(light: 0x42454EFF, dark: 0xC5C6C9FF)

        /// field/color/content/success
        public static let colorContentSuccess = SwiftUI.Color(light: 0x0B7058FF, dark: 0x5DC9AFFF)

        /// field/focus-ring/inner-shadow/blur
        public static let focusRingInnerShadowBlur: CGFloat = 0

        /// field/focus-ring/inner-shadow/inner-shadow
        public static let focusRingInnerShadowInnerShadow = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// field/focus-ring/inner-shadow/spread
        public static let focusRingInnerShadowSpread: CGFloat = 2

        /// field/focus-ring/inner-shadow/x
        public static let focusRingInnerShadowX: CGFloat = 0

        /// field/focus-ring/inner-shadow/y
        public static let focusRingInnerShadowY: CGFloat = 0

        /// field/focus-ring/outer-shadow/blur
        public static let focusRingOuterShadowBlur: CGFloat = 0

        /// field/focus-ring/outer-shadow/outer-shadow
        public static let focusRingOuterShadowOuterShadow = SwiftUI.Color(light: 0x254EDBFF, dark: 0x254EDBFF)

        /// field/focus-ring/outer-shadow/spread
        public static let focusRingOuterShadowSpread: CGFloat = 4

        /// field/focus-ring/outer-shadow/x
        public static let focusRingOuterShadowX: CGFloat = 0

        /// field/focus-ring/outer-shadow/y
        public static let focusRingOuterShadowY: CGFloat = 0

        /// field/spacing/gap
        public static let spacingGap: CGFloat = 8

        /// field/spacing/min-height
        public static let spacingMinHeight: CGFloat = 48

        /// field/spacing/padding-x
        public static let spacingPaddingX: CGFloat = 16

        /// field/spacing/padding-y
        public static let spacingPaddingY: CGFloat = 16

        /// field/typography/font-size
        public static let typographyFontSize: CGFloat = 16

        /// field/typography/font-weight
        public static let typographyFontWeight = SwiftUI.Font.Weight.medium

        /// field/typography/letter-spacing
        public static let typographyLetterSpacing: CGFloat = 0

        /// field/typography/line-height
        public static let typographyLineHeight: CGFloat = 24

        /// field/typography/text-transform
        public static let typographyTextTransform = "none"
    }

    public enum Hyperlink {
        /// hyperlink/color/default
        public static let colorDefault = SwiftUI.Color(light: 0x254EDBFF, dark: 0x6690FFFF)

        /// hyperlink/color/hover
        public static let colorHover = SwiftUI.Color(light: 0x2B59EBFF, dark: 0x84A9FFFF)
    }

    public enum Navbar {
        /// navbar/border/width/default
        public static let borderWidthDefault: CGFloat = 1

        /// navbar/color/background/default
        public static let colorBackgroundDefault = SwiftUI.Color(light: 0xFFFFFFFF, dark: 0x0D0F16FF)

        /// navbar/color/border/color/default
        public static let colorBorderColorDefault = SwiftUI.Color(light: 0xC5C6C9FF, dark: 0x42454EFF)

        /// navbar/color/border/width/default
        public static let colorBorderWidthDefault: CGFloat = 1

        /// navbar/color/content/active
        public static let colorContentActive = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// navbar/color/content/default
        public static let colorContentDefault = SwiftUI.Color(light: 0x42454EFF, dark: 0xC5C6C9FF)

        /// navbar/color/content/disabled
        public static let colorContentDisabled = SwiftUI.Color(light: 0x61646BFF, dark: 0x61646BFF)

        /// navbar/color/content/focus
        public static let colorContentFocus = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// navbar/color/content/hover
        public static let colorContentHover = SwiftUI.Color(light: 0x0D0F16FF, dark: 0xF3F4F4FF)

        /// navbar/spacing/nav-links/gap
        public static let spacingNavLinksGap: CGFloat = 48

        /// navbar/spacing/nav-links/mobile/padding-y
        public static let spacingNavLinksMobilePaddingY: CGFloat = 48

        /// navbar/spacing/padding-x
        public static let spacingPaddingX: CGFloat = 24

        /// navbar/spacing/padding-y
        public static let spacingPaddingY: CGFloat = 16
    }

    public enum Section {
        /// section/spacing/gap
        public static let spacingGap: CGFloat = 24

        /// section/spacing/padding-x
        public static let spacingPaddingX: CGFloat = 48

        /// section/spacing/padding-y
        public static let spacingPaddingY: CGFloat = 48
    }

    public enum Spacing {
        /// spacing/0
        public static let _0: CGFloat = 0

        /// spacing/12
        public static let _12: CGFloat = 12

        /// spacing/128
        public static let _128: CGFloat = 128

        /// spacing/16
        public static let _16: CGFloat = 16

        /// spacing/2
        public static let _2: CGFloat = 2

        /// spacing/24
        public static let _24: CGFloat = 24

        /// spacing/32
        public static let _32: CGFloat = 32

        /// spacing/4
        public static let _4: CGFloat = 4

        /// spacing/40
        public static let _40: CGFloat = 40

        /// spacing/48
        public static let _48: CGFloat = 48

        /// spacing/64
        public static let _64: CGFloat = 64

        /// spacing/8
        public static let _8: CGFloat = 8

        /// spacing/80
        public static let _80: CGFloat = 80

        /// spacing/96
        public static let _96: CGFloat = 96

        /// spacing/gap/lg
        public static let gapLg: CGFloat = 24

        /// spacing/gap/md
        public static let gapMd: CGFloat = 16

        /// spacing/gap/none
        public static let gapNone: CGFloat = 0

        /// spacing/gap/sm
        public static let gapSm: CGFloat = 8

        /// spacing/gap/xlg
        public static let gapXlg: CGFloat = 48

        /// spacing/gap/xsm
        public static let gapXsm: CGFloat = 4

        /// spacing/gap/xxsm
        public static let gapXxsm: CGFloat = 2

        /// spacing/padding/lg
        public static let paddingLg: CGFloat = 24

        /// spacing/padding/md
        public static let paddingMd: CGFloat = 16

        /// spacing/padding/none
        public static let paddingNone: CGFloat = 0

        /// spacing/padding/sm
        public static let paddingSm: CGFloat = 8

        /// spacing/padding/xlg
        public static let paddingXlg: CGFloat = 48

        /// spacing/padding/xsm
        public static let paddingXsm: CGFloat = 4

        /// spacing/padding/xxsm
        public static let paddingXxsm: CGFloat = 2
    }

    public enum Typography {
        /// typography/body-default/font-size
        public static let bodyDefaultFontSize: CGFloat = 16

        /// typography/body-default/font-weight
        public static let bodyDefaultFontWeight = SwiftUI.Font.Weight.regular

        /// typography/body-default/letter-spacing
        public static let bodyDefaultLetterSpacing: CGFloat = 0

        /// typography/body-default/line-height
        public static let bodyDefaultLineHeight: CGFloat = 24

        /// typography/body-default/text-transform
        public static let bodyDefaultTextTransform = "none"

        /// typography/body-emphasized/font-size
        public static let bodyEmphasizedFontSize: CGFloat = 16

        /// typography/body-emphasized/font-weight
        public static let bodyEmphasizedFontWeight = SwiftUI.Font.Weight.semibold

        /// typography/body-emphasized/letter-spacing
        public static let bodyEmphasizedLetterSpacing: CGFloat = 0

        /// typography/body-emphasized/line-height
        public static let bodyEmphasizedLineHeight: CGFloat = 24

        /// typography/body-emphasized/text-transform
        public static let bodyEmphasizedTextTransform = "none"

        /// typography/body-lg/font-size
        public static let bodyLgFontSize: CGFloat = 20

        /// typography/body-lg/font-weight
        public static let bodyLgFontWeight = SwiftUI.Font.Weight.medium

        /// typography/body-lg/letter-spacing
        public static let bodyLgLetterSpacing: CGFloat = 0

        /// typography/body-lg/line-height
        public static let bodyLgLineHeight: CGFloat = 28

        /// typography/body-lg/text-transform
        public static let bodyLgTextTransform = "none"

        /// typography/body-sm/font-size
        public static let bodySmFontSize: CGFloat = 14

        /// typography/body-sm/font-weight
        public static let bodySmFontWeight = SwiftUI.Font.Weight.regular

        /// typography/body-sm/letter-spacing
        public static let bodySmLetterSpacing: CGFloat = 0

        /// typography/body-sm/line-height
        public static let bodySmLineHeight: CGFloat = 20

        /// typography/body-sm/text-transform
        public static let bodySmTextTransform = "none"

        /// typography/display-default-mobile/font-size
        public static let displayDefaultMobileFontSize: CGFloat = 48

        /// typography/display-default-mobile/font-weight
        public static let displayDefaultMobileFontWeight = SwiftUI.Font.Weight.black

        /// typography/display-default-mobile/letter-spacing
        public static let displayDefaultMobileLetterSpacing: CGFloat = -1.5

        /// typography/display-default-mobile/line-height
        public static let displayDefaultMobileLineHeight: CGFloat = 56

        /// typography/display-default-mobile/text-transform
        public static let displayDefaultMobileTextTransform = "none"

        /// typography/display-default/font-size
        public static let displayDefaultFontSize: CGFloat = 72

        /// typography/display-default/font-weight
        public static let displayDefaultFontWeight = SwiftUI.Font.Weight.black

        /// typography/display-default/letter-spacing
        public static let displayDefaultLetterSpacing: CGFloat = -0.5

        /// typography/display-default/line-height
        public static let displayDefaultLineHeight: CGFloat = 80

        /// typography/display-default/text-transform
        public static let displayDefaultTextTransform = "none"

        /// typography/display-sm-mobile/font-size
        public static let displaySmMobileFontSize: CGFloat = 32

        /// typography/display-sm-mobile/font-weight
        public static let displaySmMobileFontWeight = SwiftUI.Font.Weight.bold

        /// typography/display-sm-mobile/letter-spacing
        public static let displaySmMobileLetterSpacing: CGFloat = -1

        /// typography/display-sm-mobile/line-height
        public static let displaySmMobileLineHeight: CGFloat = 40

        /// typography/display-sm-mobile/text-transform
        public static let displaySmMobileTextTransform = "none"

        /// typography/display-sm/font-size
        public static let displaySmFontSize: CGFloat = 40

        /// typography/display-sm/font-weight
        public static let displaySmFontWeight = SwiftUI.Font.Weight.bold

        /// typography/display-sm/letter-spacing
        public static let displaySmLetterSpacing: CGFloat = -1.5

        /// typography/display-sm/line-height
        public static let displaySmLineHeight: CGFloat = 48

        /// typography/display-sm/text-transform
        public static let displaySmTextTransform = "none"

        /// typography/font-size/104
        public static let fontSize104: CGFloat = 104

        /// typography/font-size/12
        public static let fontSize12: CGFloat = 12

        /// typography/font-size/14
        public static let fontSize14: CGFloat = 14

        /// typography/font-size/16
        public static let fontSize16: CGFloat = 16

        /// typography/font-size/18
        public static let fontSize18: CGFloat = 18

        /// typography/font-size/20
        public static let fontSize20: CGFloat = 20

        /// typography/font-size/24
        public static let fontSize24: CGFloat = 24

        /// typography/font-size/28
        public static let fontSize28: CGFloat = 28

        /// typography/font-size/32
        public static let fontSize32: CGFloat = 32

        /// typography/font-size/40
        public static let fontSize40: CGFloat = 40

        /// typography/font-size/48
        public static let fontSize48: CGFloat = 48

        /// typography/font-size/56
        public static let fontSize56: CGFloat = 56

        /// typography/font-size/64
        public static let fontSize64: CGFloat = 64

        /// typography/font-size/72
        public static let fontSize72: CGFloat = 72

        /// typography/font-size/80
        public static let fontSize80: CGFloat = 80

        /// typography/font-size/88
        public static let fontSize88: CGFloat = 88

        /// typography/font-size/96
        public static let fontSize96: CGFloat = 96

        /// typography/font-weight/400
        public static let fontWeight400 = SwiftUI.Font.Weight.regular

        /// typography/font-weight/500
        public static let fontWeight500 = SwiftUI.Font.Weight.medium

        /// typography/font-weight/600
        public static let fontWeight600 = SwiftUI.Font.Weight.semibold

        /// typography/font-weight/700
        public static let fontWeight700 = SwiftUI.Font.Weight.bold

        /// typography/font-weight/800
        public static let fontWeight800 = SwiftUI.Font.Weight.heavy

        /// typography/font-weight/900
        public static let fontWeight900 = SwiftUI.Font.Weight.black

        /// typography/font-weight/bold
        public static let fontWeightBold = "Bold"

        /// typography/font-weight/extrabold
        public static let fontWeightExtrabold = "Extra Bold"

        /// typography/font-weight/medium
        public static let fontWeightMedium = "Medium"

        /// typography/font-weight/regular
        public static let fontWeightRegular = "Regular"

        /// typography/font-weight/semi
        public static let fontWeightSemi = "Semi Bold"

        /// typography/headline-default-mobile/font-size
        public static let headlineDefaultMobileFontSize: CGFloat = 32

        /// typography/headline-default-mobile/font-weight
        public static let headlineDefaultMobileFontWeight = SwiftUI.Font.Weight.bold

        /// typography/headline-default-mobile/letter-spacing
        public static let headlineDefaultMobileLetterSpacing: CGFloat = 0.5

        /// typography/headline-default-mobile/line-height
        public static let headlineDefaultMobileLineHeight: CGFloat = 40

        /// typography/headline-default-mobile/text-transform
        public static let headlineDefaultMobileTextTransform = "none"

        /// typography/headline-default/font-size
        public static let headlineDefaultFontSize: CGFloat = 40

        /// typography/headline-default/font-weight
        public static let headlineDefaultFontWeight = SwiftUI.Font.Weight.bold

        /// typography/headline-default/letter-spacing
        public static let headlineDefaultLetterSpacing: CGFloat = 0.5

        /// typography/headline-default/line-height
        public static let headlineDefaultLineHeight: CGFloat = 48

        /// typography/headline-default/text-transform
        public static let headlineDefaultTextTransform = "none"

        /// typography/headline-lg-mobile/font-size
        public static let headlineLgMobileFontSize: CGFloat = 40

        /// typography/headline-lg-mobile/font-weight
        public static let headlineLgMobileFontWeight = SwiftUI.Font.Weight.bold

        /// typography/headline-lg-mobile/letter-spacing
        public static let headlineLgMobileLetterSpacing: CGFloat = 0.5

        /// typography/headline-lg-mobile/line-height
        public static let headlineLgMobileLineHeight: CGFloat = 48

        /// typography/headline-lg-mobile/text-transform
        public static let headlineLgMobileTextTransform = "none"

        /// typography/headline-lg/font-size
        public static let headlineLgFontSize: CGFloat = 48

        /// typography/headline-lg/font-weight
        public static let headlineLgFontWeight = SwiftUI.Font.Weight.bold

        /// typography/headline-lg/letter-spacing
        public static let headlineLgLetterSpacing: CGFloat = 0.5

        /// typography/headline-lg/line-height
        public static let headlineLgLineHeight: CGFloat = 56

        /// typography/headline-lg/text-transform
        public static let headlineLgTextTransform = "none"

        /// typography/headline-sm-mobile/font-size
        public static let headlineSmMobileFontSize: CGFloat = 28

        /// typography/headline-sm-mobile/font-weight
        public static let headlineSmMobileFontWeight = SwiftUI.Font.Weight.bold

        /// typography/headline-sm-mobile/letter-spacing
        public static let headlineSmMobileLetterSpacing: CGFloat = 0.5

        /// typography/headline-sm-mobile/line-height
        public static let headlineSmMobileLineHeight: CGFloat = 36

        /// typography/headline-sm-mobile/text-transform
        public static let headlineSmMobileTextTransform = "none"

        /// typography/headline-sm/font-size
        public static let headlineSmFontSize: CGFloat = 32

        /// typography/headline-sm/font-weight
        public static let headlineSmFontWeight = SwiftUI.Font.Weight.bold

        /// typography/headline-sm/letter-spacing
        public static let headlineSmLetterSpacing: CGFloat = 0.5

        /// typography/headline-sm/line-height
        public static let headlineSmLineHeight: CGFloat = 40

        /// typography/headline-sm/text-transform
        public static let headlineSmTextTransform = "none"

        /// typography/label-default/font-size
        public static let labelDefaultFontSize: CGFloat = 16

        /// typography/label-default/font-weight
        public static let labelDefaultFontWeight = SwiftUI.Font.Weight.medium

        /// typography/label-default/letter-spacing
        public static let labelDefaultLetterSpacing: CGFloat = 0

        /// typography/label-default/line-height
        public static let labelDefaultLineHeight: CGFloat = 24

        /// typography/label-default/text-transform
        public static let labelDefaultTextTransform = "none"

        /// typography/label-lg/font-size
        public static let labelLgFontSize: CGFloat = 20

        /// typography/label-lg/font-weight
        public static let labelLgFontWeight = SwiftUI.Font.Weight.semibold

        /// typography/label-lg/letter-spacing
        public static let labelLgLetterSpacing: CGFloat = 0

        /// typography/label-lg/line-height
        public static let labelLgLineHeight: CGFloat = 28

        /// typography/label-lg/text-transform
        public static let labelLgTextTransform = "none"

        /// typography/label-sm/font-size
        public static let labelSmFontSize: CGFloat = 14

        /// typography/label-sm/font-weight
        public static let labelSmFontWeight = SwiftUI.Font.Weight.medium

        /// typography/label-sm/letter-spacing
        public static let labelSmLetterSpacing: CGFloat = 0

        /// typography/label-sm/line-height
        public static let labelSmLineHeight: CGFloat = 20

        /// typography/label-sm/text-transform
        public static let labelSmTextTransform = "none"

        /// typography/letter-spacing/0
        public static let letterSpacing0: CGFloat = 0

        /// typography/letter-spacing/1
        public static let letterSpacing1: CGFloat = 1

        /// typography/letter-spacing/1-half
        public static let letterSpacing1Half: CGFloat = 1.5

        /// typography/letter-spacing/2
        public static let letterSpacing2: CGFloat = 2

        /// typography/letter-spacing/half
        public static let letterSpacingHalf: CGFloat = 0.5

        /// typography/letter-spacing/minus-1
        public static let letterSpacingMinus1: CGFloat = -1

        /// typography/letter-spacing/minus-1-half
        public static let letterSpacingMinus1Half: CGFloat = -1.5

        /// typography/letter-spacing/minus-2
        public static let letterSpacingMinus2: CGFloat = -2

        /// typography/letter-spacing/minus-half
        public static let letterSpacingMinusHalf: CGFloat = -0.5

        /// typography/line-height/104
        public static let lineHeight104: CGFloat = 104

        /// typography/line-height/112
        public static let lineHeight112: CGFloat = 112

        /// typography/line-height/16
        public static let lineHeight16: CGFloat = 16

        /// typography/line-height/20
        public static let lineHeight20: CGFloat = 20

        /// typography/line-height/24
        public static let lineHeight24: CGFloat = 24

        /// typography/line-height/28
        public static let lineHeight28: CGFloat = 28

        /// typography/line-height/32
        public static let lineHeight32: CGFloat = 32

        /// typography/line-height/36
        public static let lineHeight36: CGFloat = 36

        /// typography/line-height/40
        public static let lineHeight40: CGFloat = 40

        /// typography/line-height/48
        public static let lineHeight48: CGFloat = 48

        /// typography/line-height/56
        public static let lineHeight56: CGFloat = 56

        /// typography/line-height/64
        public static let lineHeight64: CGFloat = 64

        /// typography/line-height/72
        public static let lineHeight72: CGFloat = 72

        /// typography/line-height/80
        public static let lineHeight80: CGFloat = 80

        /// typography/line-height/88
        public static let lineHeight88: CGFloat = 88

        /// typography/line-height/96
        public static let lineHeight96: CGFloat = 96

        /// typography/meta-default/font-size
        public static let metaDefaultFontSize: CGFloat = 14

        /// typography/meta-default/font-weight
        public static let metaDefaultFontWeight = SwiftUI.Font.Weight.medium

        /// typography/meta-default/letter-spacing
        public static let metaDefaultLetterSpacing: CGFloat = 0

        /// typography/meta-default/line-height
        public static let metaDefaultLineHeight: CGFloat = 20

        /// typography/meta-default/text-transform
        public static let metaDefaultTextTransform = "none"

        /// typography/meta-sm/font-size
        public static let metaSmFontSize: CGFloat = 12

        /// typography/meta-sm/font-weight
        public static let metaSmFontWeight = SwiftUI.Font.Weight.medium

        /// typography/meta-sm/letter-spacing
        public static let metaSmLetterSpacing: CGFloat = 0

        /// typography/meta-sm/line-height
        public static let metaSmLineHeight: CGFloat = 16

        /// typography/meta-sm/text-transform
        public static let metaSmTextTransform = "none"

        /// typography/text-transform/capitalize
        public static let textTransformCapitalize = "capitalize"

        /// typography/text-transform/lowercase
        public static let textTransformLowercase = "lowercase"

        /// typography/text-transform/none
        public static let textTransformNone = "none"

        /// typography/text-transform/uppercase
        public static let textTransformUppercase = "uppercase"

        /// typography/title-default/font-size
        public static let titleDefaultFontSize: CGFloat = 28

        /// typography/title-default/font-weight
        public static let titleDefaultFontWeight = SwiftUI.Font.Weight.bold

        /// typography/title-default/letter-spacing
        public static let titleDefaultLetterSpacing: CGFloat = -0.5

        /// typography/title-default/line-height
        public static let titleDefaultLineHeight: CGFloat = 36

        /// typography/title-default/text-transform
        public static let titleDefaultTextTransform = "none"

        /// typography/title-lg-mobile/font-size
        public static let titleLgMobileFontSize: CGFloat = 28

        /// typography/title-lg-mobile/font-weight
        public static let titleLgMobileFontWeight = SwiftUI.Font.Weight.bold

        /// typography/title-lg-mobile/letter-spacing
        public static let titleLgMobileLetterSpacing: CGFloat = -0.5

        /// typography/title-lg-mobile/line-height
        public static let titleLgMobileLineHeight: CGFloat = 36

        /// typography/title-lg-mobile/text-transform
        public static let titleLgMobileTextTransform = "none"

        /// typography/title-lg/font-size
        public static let titleLgFontSize: CGFloat = 32

        /// typography/title-lg/font-weight
        public static let titleLgFontWeight = SwiftUI.Font.Weight.bold

        /// typography/title-lg/letter-spacing
        public static let titleLgLetterSpacing: CGFloat = -1

        /// typography/title-lg/line-height
        public static let titleLgLineHeight: CGFloat = 40

        /// typography/title-lg/text-transform
        public static let titleLgTextTransform = "none"

        /// typography/title-sm/font-size
        public static let titleSmFontSize: CGFloat = 24

        /// typography/title-sm/font-weight
        public static let titleSmFontWeight = SwiftUI.Font.Weight.medium

        /// typography/title-sm/letter-spacing
        public static let titleSmLetterSpacing: CGFloat = -0.5

        /// typography/title-sm/line-height
        public static let titleSmLineHeight: CGFloat = 32

        /// typography/title-sm/text-transform
        public static let titleSmTextTransform = "none"
    }

    /// Grid values for one layout size. Pick one with `Grid.mode(forWidth:)`.
    public struct GridMode: Sendable {
        public let columns: Int
        public let containerGutter: CGFloat
        public let defaultWidth: CGFloat
        public let maxWidth: CGFloat
        public let minWidth: CGFloat
        public let sectionGap: CGFloat
        public let sectionPadding: CGFloat
        public let viewport: String
    }

    public enum Grid {
        public static let small = GridMode(columns: 2, containerGutter: 16, defaultWidth: 375, maxWidth: 560, minWidth: 320, sectionGap: 16, sectionPadding: 16, viewport: "small")
        public static let medium = GridMode(columns: 8, containerGutter: 16, defaultWidth: 768, maxWidth: 960, minWidth: 560, sectionGap: 24, sectionPadding: 24, viewport: "medium")
        public static let large = GridMode(columns: 12, containerGutter: 24, defaultWidth: 1200, maxWidth: 1600, minWidth: 960, sectionGap: 48, sectionPadding: 48, viewport: "large")

        /// Largest mode whose minimum width fits. Use the width of the window or scene, not the device.
        public static func mode(forWidth width: CGFloat) -> GridMode {
            let modes: [GridMode] = [large, medium, small]
            return modes.first { width >= $0.minWidth } ?? small
        }
    }
}

extension SwiftUI.Color {
    /// A color that follows the current appearance, including per-view overrides
    /// such as `.preferredColorScheme(.dark)`.
    init(light: UInt32, dark: UInt32) {
        #if canImport(UIKit)
        self.init(uiColor: UIColor { traits in
            traits.userInterfaceStyle == .dark ? UIColor(rgba: dark) : UIColor(rgba: light)
        })
        #elseif canImport(AppKit)
        self.init(nsColor: NSColor(name: nil) { appearance in
            appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? NSColor(rgba: dark) : NSColor(rgba: light)
        })
        #endif
    }
}

#if canImport(UIKit)
private extension UIColor {
    convenience init(rgba: UInt32) {
        self.init(red: CGFloat((rgba >> 24) & 0xFF) / 255, green: CGFloat((rgba >> 16) & 0xFF) / 255,
                  blue: CGFloat((rgba >> 8) & 0xFF) / 255, alpha: CGFloat(rgba & 0xFF) / 255)
    }
}
#elseif canImport(AppKit)
private extension NSColor {
    convenience init(rgba: UInt32) {
        self.init(srgbRed: CGFloat((rgba >> 24) & 0xFF) / 255, green: CGFloat((rgba >> 16) & 0xFF) / 255,
                  blue: CGFloat((rgba >> 8) & 0xFF) / 255, alpha: CGFloat(rgba & 0xFF) / 255)
    }
}
#endif
