#!/usr/bin/env node
// Builds platform outputs from tokens/*.json.
//
//   platforms/web/tokens.css                     CSS custom properties, rem units
//   platforms/ios/Sources/SoftwareTokens/*.swift SwiftUI, points, dynamic light/dark colors
//   platforms/android/.../SoftwareTokens.kt      Jetpack Compose, dp/sp, light/dark colors
//
// Usage: node scripts/build.mjs

import { loadTokens, publicKeys, layoutKeys, lookup, resolve, aliasKey, isPrivate, hex8, write } from './lib/tokens.mjs';

const HEADER = 'Generated by scripts/build.mjs from tokens/*.json. Do not edit; change the Figma variables and export.';
const ROOT_FONT_SIZE = 16; // 1rem = 16px = 16pt = 16dp

// Web fallback after every font-family token: the OS system sans-serif, then Helvetica.
// system-ui is the standard keyword; -apple-system, BlinkMacSystemFont, "Segoe UI" and Roboto
// name the same OS fonts for browsers that predate it. sans-serif is the last resort.
// Native needs no stack: iOS and Android fall back to their system font automatically.
const FONT_FALLBACK = ['system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'Helvetica', 'sans-serif'];

const model = loadTokens();
const semanticDefault = model.semanticModes[0];
const layoutBase = model.layoutModes[0];
const baseCtx = { semantic: semanticDefault, layout: layoutBase };
const keys = publicKeys(model);

// ─── Web ────────────────────────────────────────────────────────────────────

function rem(px) {
  if (px === 0) return '0';
  return `${Number((px / ROOT_FONT_SIZE).toFixed(4))}rem`;
}

function cssVar(key) {
  return '--' + key.replace(/\./g, '-');
}

function cssLiteral(token) {
  switch (token.type) {
    case 'color': {
      const h = hex8(token.value).toLowerCase();
      return '#' + (h.endsWith('ff') ? h.slice(0, 6) : h);
    }
    case 'dimension':
      if (token.value.unit !== 'px') throw new Error(`Unsupported unit ${token.value.unit} on ${token.path.join('.')}`);
      return rem(token.value.value);
    case 'fontFamily': {
      const family = `"${token.value}"`;
      return [family, ...FONT_FALLBACK.filter((f) => f.replace(/"/g, '') !== token.value)].join(', ');
    }
    default:
      return String(token.value);
  }
}

// References stay live as var() so a theme only has to override semantic tokens;
// references to internal primitives are inlined.
function cssValue(key, ctx) {
  const token = lookup(model, key, ctx);
  const target = aliasKey(token.value);
  if (target && !isPrivate(model, target)) return `var(${cssVar(target)})`;
  return cssLiteral(target ? resolve(model, key, ctx) : token);
}

function block(selector, entries, indent = '') {
  if (!entries.length) return '';
  const body = entries.map(([k, v]) => `${indent}  ${k}: ${v};`).join('\n');
  return `${indent}${selector} {\n${body}\n${indent}}\n`;
}

function buildCss() {
  const out = [`/* ${HEADER} */\n`];

  // Theme-independent and default-theme tokens. [data-theme] re-declares them on any
  // themed subtree so var() references resolve against that subtree's colors.
  const isType = (k) => model.tierOf(k) === 'typography';
  out.push(block(':root,\n[data-theme]', keys.filter((k) => !isType(k)).map((k) => [cssVar(k), cssValue(k, baseCtx)])));
  // Typography gets its own selector for the same reason: [data-typography] re-declares it so a
  // brand's font families reach every text style. Kept apart so it never resets theme colors.
  out.push(block(':root,\n[data-typography]', keys.filter(isType).map((k) => [cssVar(k), cssValue(k, baseCtx)])));
  out.push(block(':root', [['color-scheme', 'light dark']]));

  const layoutEntries = (mode) => layoutKeys(model).map((k) => [cssVar(k), cssValue(k, { semantic: semanticDefault, layout: mode })]);
  out.push(block(':root', layoutEntries(layoutBase)));
  for (const mode of model.layoutModes.slice(1)) {
    const minWidth = model.layout[mode].get('min-width').value.value;
    // em, not rem: media queries resolve em against the browser default, so they track user font-size settings.
    out.push(`@media (min-width: ${Number((minWidth / ROOT_FONT_SIZE).toFixed(4))}em) {\n${block(':root', layoutEntries(mode), '  ')}}\n`);
  }

  // Other semantic modes: only tokens whose output differs from the default theme.
  for (const mode of model.semanticModes.slice(1)) {
    const ctx = { semantic: mode, layout: layoutBase };
    const diff = keys.filter((k) => model.tierOf(k) === 'semantic' && cssValue(k, ctx) !== cssValue(k, baseCtx)).map((k) => [cssVar(k), cssValue(k, ctx)]);
    const withScheme = mode === 'dark' || mode === 'light' ? [['color-scheme', mode], ...diff] : diff;
    if (mode === 'dark') {
      out.push(`@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme="light"])', withScheme, '  ')}}\n`);
    }
    out.push(block(`[data-theme="${mode}"]`, withScheme));
  }
  out.push(block(`[data-theme="${semanticDefault}"]`, [['color-scheme', semanticDefault === 'dark' ? 'dark' : 'light']]));

  // Other typography modes (brands): only tokens whose output differs from the default mode.
  // Opt in per subtree with data-typography="<mode>". Native outputs use the default mode.
  for (const mode of model.typographyModes.slice(1)) {
    const ctx = { ...baseCtx, typography: mode };
    const diff = keys.filter((k) => model.tierOf(k) === 'typography' && cssValue(k, ctx) !== cssValue(k, baseCtx)).map((k) => [cssVar(k), cssValue(k, ctx)]);
    out.push(block(`[data-typography="${mode}"]`, diff));
  }

  return out.filter(Boolean).join('\n');
}

// ─── Native naming ──────────────────────────────────────────────────────────

const SWIFT_KEYWORDS = new Set(['associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate', 'func', 'import', 'init', 'inout', 'internal', 'let', 'open', 'operator', 'private', 'protocol', 'public', 'rethrows', 'static', 'struct', 'subscript', 'typealias', 'var', 'break', 'case', 'continue', 'default', 'defer', 'do', 'else', 'fallthrough', 'for', 'guard', 'if', 'in', 'repeat', 'return', 'switch', 'where', 'while', 'as', 'catch', 'false', 'is', 'nil', 'super', 'self', 'Self', 'throw', 'throws', 'true', 'try']);
const KOTLIN_KEYWORDS = new Set(['as', 'break', 'class', 'continue', 'do', 'else', 'false', 'for', 'fun', 'if', 'in', 'interface', 'is', 'null', 'object', 'package', 'return', 'super', 'this', 'throw', 'true', 'try', 'typealias', 'typeof', 'val', 'var', 'when', 'while']);

function words(segments) {
  return segments.flatMap((s) => s.split('-')).filter(Boolean);
}

function camel(segments) {
  const w = words(segments);
  const name = w.map((x, i) => (i === 0 ? x : x[0].toUpperCase() + x.slice(1))).join('');
  return /^\d/.test(name) ? '_' + name : name;
}

function pascal(segment) {
  return words([segment]).map((x) => x[0].toUpperCase() + x.slice(1)).join('');
}

function escape(name, reserved, quote) {
  return reserved.has(name) ? quote + name + quote : name;
}

// Native apps use the platform system font (San Francisco, the device default on Android),
// so font-family tokens are web-only. Sizes, weights, line heights and tracking still apply.
function nativeKeys() {
  return keys.filter((k) => resolve(model, k, baseCtx).type !== 'fontFamily');
}

// Groups public tokens by first path segment: color.background.default → Color.backgroundDefault
function groups() {
  const map = new Map();
  for (const key of nativeKeys()) {
    const path = key.split('.');
    if (path.length < 2) throw new Error(`Token "${key}" needs at least two name segments for native output`);
    const group = pascal(path[0]);
    const member = camel(path.slice(1));
    if (!map.has(group)) map.set(group, new Map());
    const members = map.get(group);
    if (members.has(member)) throw new Error(`"${key}" and "${members.get(member)}" both become ${group}.${member}`);
    members.set(member, key);
  }
  return map;
}

function isTextMetric(key) {
  return /(^|\.)(font-size|line-height|letter-spacing)(\.|$)/.test(key);
}

function colorModes(key) {
  const light = model.semanticModes.includes('light') ? 'light' : semanticDefault;
  const dark = model.semanticModes.includes('dark') ? 'dark' : light;
  return {
    light: hex8(resolve(model, key, { semantic: light, layout: layoutBase }).value),
    dark: hex8(resolve(model, key, { semantic: dark, layout: layoutBase }).value),
  };
}

const SWIFT_WEIGHTS = { 100: 'ultraLight', 200: 'thin', 300: 'light', 400: 'regular', 500: 'medium', 600: 'semibold', 700: 'bold', 800: 'heavy', 900: 'black' };

// ─── iOS (SwiftUI) ──────────────────────────────────────────────────────────

function swiftValue(key, ctx) {
  const t = resolve(model, key, ctx);
  switch (t.type) {
    case 'color': {
      const { light, dark } = colorModes(key);
      return `SwiftUI.Color(light: 0x${light}, dark: 0x${dark})`;
    }
    case 'dimension': return { decl: 'CGFloat', value: String(t.value.value) };
    case 'fontWeight': {
      const w = SWIFT_WEIGHTS[t.value];
      if (!w) throw new Error(`No SwiftUI weight for ${t.value} on ${key}`);
      return `SwiftUI.Font.Weight.${w}`;
    }
    case 'number': return { decl: 'Int', value: String(t.value) };
    default: return JSON.stringify(String(t.value));
  }
}

function swiftDecl(name, key, ctx, indent) {
  const v = swiftValue(key, ctx);
  const n = escape(name, SWIFT_KEYWORDS, '`');
  const doc = `${indent}/// ${key.replace(/\./g, '/')}\n`;
  return typeof v === 'object' ? `${doc}${indent}public static let ${n}: ${v.decl} = ${v.value}` : `${doc}${indent}public static let ${n} = ${v}`;
}

function buildSwift() {
  const lines = [
    `// ${HEADER}`,
    '',
    'import SwiftUI',
    '#if canImport(UIKit)',
    'import UIKit',
    '#elseif canImport(AppKit)',
    'import AppKit',
    '#endif',
    '',
    '/// Design tokens. Sizes are points (1pt = 1px = 1/16rem); colors follow the system appearance.',
    'public enum SoftwareTokens {',
  ];
  for (const [group, members] of groups()) {
    lines.push(`    public enum ${group} {`);
    lines.push([...members].map(([name, key]) => swiftDecl(name, key, baseCtx, '        ')).join('\n\n'));
    lines.push('    }', '');
  }

  // Layout: one value set per grid mode.
  const lk = layoutKeys(model);
  lines.push('    /// Grid values for one layout size. Pick one with `Grid.mode(forWidth:)`.');
  lines.push('    public struct GridMode: Sendable {');
  for (const k of lk) {
    const t = resolve(model, k, baseCtx);
    const type = t.type === 'dimension' ? 'CGFloat' : t.type === 'number' ? 'Int' : 'String';
    lines.push(`        public let ${camel(k.split('.'))}: ${type}`);
  }
  lines.push('    }', '');
  lines.push('    public enum Grid {');
  for (const mode of model.layoutModes) {
    const args = lk.map((k) => {
      const t = resolve(model, k, { semantic: semanticDefault, layout: mode });
      const v = t.type === 'dimension' ? String(t.value.value) : t.type === 'number' ? String(t.value) : JSON.stringify(String(t.value));
      return `${camel(k.split('.'))}: ${v}`;
    });
    lines.push(`        public static let ${camel([mode])} = GridMode(${args.join(', ')})`);
  }
  lines.push('');
  lines.push('        /// Largest mode whose minimum width fits. Use the width of the window or scene, not the device.');
  lines.push('        public static func mode(forWidth width: CGFloat) -> GridMode {');
  lines.push(`            let modes: [GridMode] = [${[...model.layoutModes].reverse().map((m) => camel([m])).join(', ')}]`);
  lines.push(`            return modes.first { width >= $0.minWidth } ?? ${camel([layoutBase])}`);
  lines.push('        }');
  lines.push('    }');
  lines.push('}', '');

  lines.push(
    'extension SwiftUI.Color {',
    '    /// A color that follows the current appearance, including per-view overrides',
    '    /// such as `.preferredColorScheme(.dark)`.',
    '    init(light: UInt32, dark: UInt32) {',
    '        #if canImport(UIKit)',
    '        self.init(uiColor: UIColor { traits in',
    '            traits.userInterfaceStyle == .dark ? UIColor(rgba: dark) : UIColor(rgba: light)',
    '        })',
    '        #elseif canImport(AppKit)',
    '        self.init(nsColor: NSColor(name: nil) { appearance in',
    '            appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua ? NSColor(rgba: dark) : NSColor(rgba: light)',
    '        })',
    '        #endif',
    '    }',
    '}',
    '',
    '#if canImport(UIKit)',
    'private extension UIColor {',
    '    convenience init(rgba: UInt32) {',
    '        self.init(red: CGFloat((rgba >> 24) & 0xFF) / 255, green: CGFloat((rgba >> 16) & 0xFF) / 255,',
    '                  blue: CGFloat((rgba >> 8) & 0xFF) / 255, alpha: CGFloat(rgba & 0xFF) / 255)',
    '    }',
    '}',
    '#elseif canImport(AppKit)',
    'private extension NSColor {',
    '    convenience init(rgba: UInt32) {',
    '        self.init(srgbRed: CGFloat((rgba >> 24) & 0xFF) / 255, green: CGFloat((rgba >> 16) & 0xFF) / 255,',
    '                  blue: CGFloat((rgba >> 8) & 0xFF) / 255, alpha: CGFloat(rgba & 0xFF) / 255)',
    '    }',
    '}',
    '#endif',
    '',
  );
  return lines.join('\n');
}

// ─── Android (Jetpack Compose) ──────────────────────────────────────────────

function argb(hex) {
  return '0x' + hex.slice(6, 8) + hex.slice(0, 6);
}

function kotlinDecl(name, key, indent) {
  const t = resolve(model, key, baseCtx);
  const n = escape(name, KOTLIN_KEYWORDS, '`');
  const doc = `${indent}/** ${key.replace(/\./g, '/')} */\n`;
  switch (t.type) {
    case 'color': {
      const { light, dark } = colorModes(key);
      if (light === dark) return `${doc}${indent}val ${n} = ComposeColor(${argb(light)})`;
      return `${doc}${indent}val ${n}: ComposeColor\n${indent}    @Composable @ReadOnlyComposable\n${indent}    get() = if (isSoftwareDarkTheme()) ComposeColor(${argb(dark)}) else ComposeColor(${argb(light)})`;
    }
    case 'dimension': {
      const v = t.value.value;
      return `${doc}${indent}val ${n} = ${v < 0 ? `(${v})` : v}.${isTextMetric(key) ? 'sp' : 'dp'}`;
    }
    case 'fontWeight': return `${doc}${indent}val ${n} = FontWeight(${t.value})`;
    case 'number': return `${doc}${indent}const val ${n} = ${t.value}`;
    default: return `${doc}${indent}const val ${n} = ${JSON.stringify(String(t.value))}`;
  }
}

function buildKotlin() {
  const lines = [
    `// ${HEADER}`,
    '',
    'package design.hobbs.software.tokens',
    '',
    'import androidx.compose.foundation.isSystemInDarkTheme',
    'import androidx.compose.runtime.Composable',
    'import androidx.compose.runtime.Immutable',
    'import androidx.compose.runtime.ReadOnlyComposable',
    'import androidx.compose.runtime.staticCompositionLocalOf',
    'import androidx.compose.ui.graphics.Color as ComposeColor',
    'import androidx.compose.ui.text.font.FontWeight',
    'import androidx.compose.ui.unit.Dp',
    'import androidx.compose.ui.unit.dp',
    'import androidx.compose.ui.unit.sp',
    '',
    '/** Forces a theme for a subtree: true = dark, false = light, null = follow the system setting. */',
    'val LocalSoftwareDarkTheme = staticCompositionLocalOf<Boolean?> { null }',
    '',
    '@Composable',
    '@ReadOnlyComposable',
    'fun isSoftwareDarkTheme(): Boolean = LocalSoftwareDarkTheme.current ?: isSystemInDarkTheme()',
    '',
    '/** Design tokens. Sizes are dp (text metrics sp, so they follow the font-scale setting). */',
    'object SoftwareTokens {',
  ];
  for (const [group, members] of groups()) {
    lines.push(`    object ${group} {`);
    lines.push([...members].map(([name, key]) => kotlinDecl(name, key, '        ')).join('\n\n'));
    lines.push('    }', '');
  }

  const lk = layoutKeys(model);
  lines.push('    /** Grid values for one layout size. Pick one with [Grid.forWidth]. */');
  lines.push('    @Immutable');
  lines.push('    data class GridMode(');
  for (const k of lk) {
    const t = resolve(model, k, baseCtx);
    const type = t.type === 'dimension' ? 'Dp' : t.type === 'number' ? 'Int' : 'String';
    lines.push(`        val ${camel(k.split('.'))}: ${type},`);
  }
  lines.push('    )', '');
  lines.push('    object Grid {');
  for (const mode of model.layoutModes) {
    const args = lk.map((k) => {
      const t = resolve(model, k, { semantic: semanticDefault, layout: mode });
      const v = t.type === 'dimension' ? `${t.value.value}.dp` : t.type === 'number' ? String(t.value) : JSON.stringify(String(t.value));
      return `            ${camel(k.split('.'))} = ${v},`;
    });
    lines.push(`        val ${camel([mode])} = GridMode(\n${args.join('\n')}\n        )`);
  }
  lines.push('');
  lines.push('        /** Largest mode whose minimum width fits. Use the window width, not the screen. */');
  lines.push('        fun forWidth(width: Dp): GridMode =');
  lines.push(`            listOf(${[...model.layoutModes].reverse().map((m) => camel([m])).join(', ')}).firstOrNull { width >= it.minWidth } ?: ${camel([layoutBase])}`);
  lines.push('    }');
  lines.push('}', '');
  return lines.join('\n');
}

// ─── Write ──────────────────────────────────────────────────────────────────

write('platforms/web/tokens.css', buildCss());
write('platforms/ios/Sources/SoftwareTokens/SoftwareTokens.swift', buildSwift());
write('platforms/android/src/main/kotlin/design/hobbs/software/tokens/SoftwareTokens.kt', buildKotlin());

console.log(`Built ${keys.length} tokens + ${layoutKeys(model).length} grid tokens × ${model.layoutModes.length} modes`);
console.log(`Themes: ${model.semanticModes.join(', ')}  |  Grid: ${model.layoutModes.join(' < ')}`);
