#!/usr/bin/env node
// Downloads Inter from Google Fonts for self-hosting and writes platforms/web/fonts.css.
// Run again to pick up a newer Inter release. Usage: node scripts/fonts.mjs
//
// Google serves Inter as a variable font (all weights, 100–900) split by script, so a page
// only downloads the subsets its characters need. The files are SIL Open Font License.

import { write, ROOT } from './lib/tokens.mjs';
import fs from 'node:fs';
import path from 'node:path';

const CSS_URL = 'https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap';
const LICENSE_URL = 'https://raw.githubusercontent.com/google/fonts/main/ofl/inter/OFL.txt';
// Google picks the font format from the user agent; this one gets woff2.
const USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36';
const FONT_DIR = 'platforms/web/fonts';

async function get(url, as) {
  const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT } });
  if (!res.ok) throw new Error(`${url} → ${res.status}`);
  return as === 'bytes' ? Buffer.from(await res.arrayBuffer()) : res.text();
}

const css = await get(CSS_URL);
const faces = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*@font-face \{([^}]+)\}/g)].map(([, subset, body]) => ({
  subset,
  style: body.match(/font-style: (\w+);/)[1],
  weight: body.match(/font-weight: ([\d ]+);/)[1],
  url: body.match(/url\((https:[^)]+\.woff2)\)/)[1],
  range: body.match(/unicode-range: ([^;]+);/)[1],
}));
if (!faces.length) throw new Error('No @font-face rules found; Google Fonts response format changed');

fs.rmSync(path.join(ROOT, FONT_DIR), { recursive: true, force: true });
const blocks = [];
for (const face of faces) {
  const file = `inter-${face.style}-${face.subset}.woff2`;
  const bytes = await get(face.url, 'bytes');
  if (bytes.subarray(0, 4).toString('latin1') !== 'wOF2') throw new Error(`${face.url} is not a woff2 file`);
  write(`${FONT_DIR}/${file}`, bytes);
  console.log(`${String(bytes.length).padStart(8)} B  ${file}`);
  blocks.push(`/* ${face.subset} */
@font-face {
  font-family: "Inter";
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url("fonts/${file}") format("woff2");
  unicode-range: ${face.range};
}`);
}
write(`${FONT_DIR}/OFL.txt`, await get(LICENSE_URL));

const version = css.match(/\/s\/inter\/(v\d+)\//)?.[1] ?? 'unknown';
write('platforms/web/fonts.css', `/* Inter ${version}, self-hosted from Google Fonts (SIL Open Font License, fonts/OFL.txt).
   Generated by scripts/fonts.mjs. Variable font: every weight 100–900 per file.
   Browsers download only the subsets whose unicode-range matches characters on the page. */

${blocks.join('\n\n')}
`);
console.log(`Inter ${version}: ${faces.length} files + OFL.txt → ${FONT_DIR}/, platforms/web/fonts.css`);
