// Generated by scripts/build.mjs from tokens/*.json. Do not edit; change the Figma variables and export.

package design.hobbs.software.tokens

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color as ComposeColor
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Forces a theme for a subtree: true = dark, false = light, null = follow the system setting. */
val LocalSoftwareDarkTheme = staticCompositionLocalOf<Boolean?> { null }

@Composable
@ReadOnlyComposable
fun isSoftwareDarkTheme(): Boolean = LocalSoftwareDarkTheme.current ?: isSystemInDarkTheme()

/** Design tokens. Sizes are dp (text metrics sp, so they follow the font-scale setting). */
object SoftwareTokens {
    object Accordion {
        /** accordion/border/radius/default */
        val borderRadiusDefault = 8.dp

        /** accordion/border/width/default */
        val borderWidthDefault = 1.dp

        /** accordion/color/background/default */
        val colorBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** accordion/color/border/default */
        val colorBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFFC5C6C9)

        /** accordion/color/border/hover */
        val colorBorderHover = ComposeColor(0xFF6F7078)

        /** accordion/color/content/active */
        val colorContentActive: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** accordion/color/content/default */
        val colorContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF8C8F9B) else ComposeColor(0xFF6F7078)

        /** accordion/color/content/disabled */
        val colorContentDisabled = ComposeColor(0xFF61646B)

        /** accordion/color/content/focus */
        val colorContentFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** accordion/color/content/hover */
        val colorContentHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** accordion/spacing/gap */
        val spacingGap = 16.dp

        /** accordion/spacing/padding-x */
        val spacingPaddingX = 24.dp

        /** accordion/spacing/padding-y */
        val spacingPaddingY = 16.dp
    }

    object Alert {
        /** alert/border/radius/default */
        val borderRadiusDefault = 4.dp

        /** alert/border/width/default */
        val borderWidthDefault = 1.dp

        /** alert/color/error/background/default */
        val colorErrorBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF390E0E) else ComposeColor(0xFFFCEAEF)

        /** alert/color/error/border/default */
        val colorErrorBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFDD7C88) else ComposeColor(0xFF8D2121)

        /** alert/color/error/content/default */
        val colorErrorContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFA2B2) else ComposeColor(0xFFB82F30)

        /** alert/color/info/background/default */
        val colorInfoBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF15193F) else ComposeColor(0xFFECEEFC)

        /** alert/color/info/border/default */
        val colorInfoBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF8792EA) else ComposeColor(0xFF34409E)

        /** alert/color/info/content/default */
        val colorInfoContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFABB3F0) else ComposeColor(0xFF4555D3)

        /** alert/color/success/background/default */
        val colorSuccessBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF03211A) else ComposeColor(0xFFDCF3EE)

        /** alert/color/success/border/default */
        val colorSuccessBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF11AD86) else ComposeColor(0xFF085442)

        /** alert/color/success/content/default */
        val colorSuccessContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF5DC9AF) else ComposeColor(0xFF0B7058)

        /** alert/color/warning/background/default */
        val colorWarningBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF2C1900) else ComposeColor(0xFFF9EFBB)

        /** alert/color/warning/border/default */
        val colorWarningBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFDBB305) else ComposeColor(0xFF6D3F00)

        /** alert/color/warning/content/default */
        val colorWarningContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFD242) else ComposeColor(0xFF8A5801)

        /** alert/spacing/gap */
        val spacingGap = 8.dp

        /** alert/spacing/min-height */
        val spacingMinHeight = 48.dp

        /** alert/spacing/padding-x */
        val spacingPaddingX = 16.dp

        /** alert/spacing/padding-y */
        val spacingPaddingY = 8.dp
    }

    object Border {
        /** border/radius/lg */
        val radiusLg = 24.dp

        /** border/radius/md */
        val radiusMd = 16.dp

        /** border/radius/none */
        val radiusNone = 0.dp

        /** border/radius/round */
        val radiusRound = 9999.dp

        /** border/radius/sm */
        val radiusSm = 8.dp

        /** border/radius/xlg */
        val radiusXlg = 48.dp

        /** border/radius/xsm */
        val radiusXsm = 4.dp

        /** border/radius/xxsm */
        val radiusXxsm = 2.dp

        /** border/width/default */
        val widthDefault = 1.dp

        /** border/width/lg */
        val widthLg = 8.dp

        /** border/width/md */
        val widthMd = 4.dp

        /** border/width/sm */
        val widthSm = 2.dp
    }

    object Button {
        /** button/border/radius/default */
        val borderRadiusDefault = 4.dp

        /** button/border/radius/focus */
        val borderRadiusFocus = 4.dp

        /** button/border/radius/hover */
        val borderRadiusHover = 4.dp

        /** button/border/radius/lg */
        val borderRadiusLg = 24.dp

        /** button/border/radius/md */
        val borderRadiusMd = 16.dp

        /** button/border/radius/round */
        val borderRadiusRound = 9999.dp

        /** button/border/radius/sm */
        val borderRadiusSm = 8.dp

        /** button/border/radius/xlg */
        val borderRadiusXlg = 48.dp

        /** button/border/width/default */
        val borderWidthDefault = 1.dp

        /** button/border/width/hover */
        val borderWidthHover = 1.dp

        /** button/color/danger/background/default */
        val colorDangerBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** button/color/danger/background/focus */
        val colorDangerBackgroundFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF390E0E) else ComposeColor(0xFFFCEAEF)

        /** button/color/danger/background/hover */
        val colorDangerBackgroundHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF390E0E) else ComposeColor(0xFFFCEAEF)

        /** button/color/danger/border/default */
        val colorDangerBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFDD7C88) else ComposeColor(0xFF8D2121)

        /** button/color/danger/border/focus */
        val colorDangerBorderFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFDD7C88) else ComposeColor(0xFF8D2121)

        /** button/color/danger/border/hover */
        val colorDangerBorderHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFA2B2) else ComposeColor(0xFFB82F30)

        /** button/color/danger/content/default */
        val colorDangerContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFA2B2) else ComposeColor(0xFFB82F30)

        /** button/color/danger/content/focus */
        val colorDangerContentFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFA2B2) else ComposeColor(0xFFB82F30)

        /** button/color/danger/content/hover */
        val colorDangerContentHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFA2B2) else ComposeColor(0xFFB82F30)

        /** button/color/disabled/background/default */
        val colorDisabledBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF3F4F4)

        /** button/color/disabled/border/default */
        val colorDisabledBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFF6F7078)

        /** button/color/disabled/content/default */
        val colorDisabledContentDefault = ComposeColor(0xFF61646B)

        /** button/color/outline/background/default */
        val colorOutlineBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** button/color/outline/background/disabled */
        val colorOutlineBackgroundDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF3F4F4)

        /** button/color/outline/background/focus */
        val colorOutlineBackgroundFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF7F7F7)

        /** button/color/outline/background/hover */
        val colorOutlineBackgroundHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF7F7F7)

        /** button/color/outline/border/default */
        val colorOutlineBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** button/color/outline/border/disabled */
        val colorOutlineBorderDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFF6F7078)

        /** button/color/outline/border/focus */
        val colorOutlineBorderFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/color/outline/border/hover */
        val colorOutlineBorderHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/color/outline/content/default */
        val colorOutlineContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** button/color/outline/content/disabled */
        val colorOutlineContentDisabled = ComposeColor(0xFF61646B)

        /** button/color/outline/content/focus */
        val colorOutlineContentFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/color/outline/content/hover */
        val colorOutlineContentHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/color/primary/background/default */
        val colorPrimaryBackgroundDefault = ComposeColor(0xFF003E4C)

        /** button/color/primary/background/disabled */
        val colorPrimaryBackgroundDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF3F4F4)

        /** button/color/primary/background/focus */
        val colorPrimaryBackgroundFocus = ComposeColor(0xFF002436)

        /** button/color/primary/background/hover */
        val colorPrimaryBackgroundHover = ComposeColor(0xFF002436)

        /** button/color/primary/border/default */
        val colorPrimaryBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** button/color/primary/border/disabled */
        val colorPrimaryBorderDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFF6F7078)

        /** button/color/primary/border/focus */
        val colorPrimaryBorderFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/color/primary/border/hover */
        val colorPrimaryBorderHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/color/primary/content/default */
        val colorPrimaryContentDefault = ComposeColor(0xFFF3F4F4)

        /** button/color/primary/content/disabled */
        val colorPrimaryContentDisabled = ComposeColor(0xFF61646B)

        /** button/color/primary/content/focus */
        val colorPrimaryContentFocus = ComposeColor(0xFFF3F4F4)

        /** button/color/primary/content/hover */
        val colorPrimaryContentHover = ComposeColor(0xFFF3F4F4)

        /** button/color/quiet/background/default */
        val colorQuietBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** button/color/quiet/background/disabled */
        val colorQuietBackgroundDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF3F4F4)

        /** button/color/quiet/background/focus */
        val colorQuietBackgroundFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** button/color/quiet/background/hover */
        val colorQuietBackgroundHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF7F7F7)

        /** button/color/quiet/border/default */
        val colorQuietBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** button/color/quiet/border/disabled */
        val colorQuietBorderDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFF6F7078)

        /** button/color/quiet/border/focus */
        val colorQuietBorderFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/color/quiet/border/hover */
        val colorQuietBorderHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/color/quiet/content/default */
        val colorQuietContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** button/color/quiet/content/disabled */
        val colorQuietContentDisabled = ComposeColor(0xFF61646B)

        /** button/color/quiet/content/focus */
        val colorQuietContentFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** button/color/quiet/content/hover */
        val colorQuietContentHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** button/focus-ring/inner-shadow/blur */
        val focusRingInnerShadowBlur = 0.dp

        /** button/focus-ring/inner-shadow/inner-shadow */
        val focusRingInnerShadowInnerShadow: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** button/focus-ring/inner-shadow/spread */
        val focusRingInnerShadowSpread = 2.dp

        /** button/focus-ring/inner-shadow/x */
        val focusRingInnerShadowX = 0.dp

        /** button/focus-ring/inner-shadow/y */
        val focusRingInnerShadowY = 0.dp

        /** button/focus-ring/outer-shadow/blur */
        val focusRingOuterShadowBlur = 0.dp

        /** button/focus-ring/outer-shadow/outer-shadow */
        val focusRingOuterShadowOuterShadow: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF002436) else ComposeColor(0xFF003E4C)

        /** button/focus-ring/outer-shadow/spread */
        val focusRingOuterShadowSpread = 4.dp

        /** button/focus-ring/outer-shadow/x */
        val focusRingOuterShadowX = 0.dp

        /** button/focus-ring/outer-shadow/y */
        val focusRingOuterShadowY = 0.dp

        /** button/spacing/default/gap */
        val spacingDefaultGap = 8.dp

        /** button/spacing/default/min-height */
        val spacingDefaultMinHeight = 48.dp

        /** button/spacing/default/padding-x */
        val spacingDefaultPaddingX = 16.dp

        /** button/spacing/default/padding-y */
        val spacingDefaultPaddingY = 8.dp

        /** button/spacing/groups/gap */
        val spacingGroupsGap = 16.dp

        /** button/spacing/groups/padding-y */
        val spacingGroupsPaddingY = 16.dp

        /** button/typography/font-size */
        val typographyFontSize = 14.sp

        /** button/typography/font-weight */
        val typographyFontWeight = FontWeight(500)

        /** button/typography/letter-spacing */
        val typographyLetterSpacing = 0.5.sp

        /** button/typography/line-height */
        val typographyLineHeight = 20.sp

        /** button/typography/text-transform */
        const val typographyTextTransform = "capitalize"
    }

    object Chip {
        /** chip/border/radius/default */
        val borderRadiusDefault = 9999.dp

        /** chip/border/width/default */
        val borderWidthDefault = 1.dp

        /** chip/color/default/background/default */
        val colorDefaultBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** chip/color/default/border/default */
        val colorDefaultBorderDefault = ComposeColor(0xFF6F7078)

        /** chip/color/default/content/default */
        val colorDefaultContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** chip/color/draft/background/default */
        val colorDraftBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF15193F) else ComposeColor(0xFFECEEFC)

        /** chip/color/draft/border/default */
        val colorDraftBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF8792EA) else ComposeColor(0xFF34409E)

        /** chip/color/draft/content/default */
        val colorDraftContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFABB3F0) else ComposeColor(0xFF4555D3)

        /** chip/color/error/background/default */
        val colorErrorBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF390E0E) else ComposeColor(0xFFFCEAEF)

        /** chip/color/error/border/default */
        val colorErrorBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFDD7C88) else ComposeColor(0xFF8D2121)

        /** chip/color/error/content/default */
        val colorErrorContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFA2B2) else ComposeColor(0xFFB82F30)

        /** chip/color/partial/background/default */
        val colorPartialBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** chip/color/partial/border/default */
        val colorPartialBorderDefault = ComposeColor(0xFF6F7078)

        /** chip/color/partial/content/default */
        val colorPartialContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** chip/color/sent/background/default */
        val colorSentBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** chip/color/sent/border/default */
        val colorSentBorderDefault = ComposeColor(0xFF6F7078)

        /** chip/color/sent/content/default */
        val colorSentContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** chip/color/success/background/default */
        val colorSuccessBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF03211A) else ComposeColor(0xFFDCF3EE)

        /** chip/color/success/border/default */
        val colorSuccessBorderDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF11AD86) else ComposeColor(0xFF085442)

        /** chip/color/success/content/default */
        val colorSuccessContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF5DC9AF) else ComposeColor(0xFF0B7058)

        /** chip/spacing/default/padding-x */
        val spacingDefaultPaddingX = 4.dp

        /** chip/spacing/default/padding-y */
        val spacingDefaultPaddingY = 2.dp

        /** chip/spacing/groups/gap */
        val spacingGroupsGap = 4.dp
    }

    object Color {
        /** color/background/brand */
        val backgroundBrand = ComposeColor(0xFF003E4C)

        /** color/background/brand-hover */
        val backgroundBrandHover = ComposeColor(0xFF002436)

        /** color/background/default */
        val backgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** color/background/disabled */
        val backgroundDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF3F4F4)

        /** color/background/knockout */
        val backgroundKnockout: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFF252525)

        /** color/background/knockout-hover */
        val backgroundKnockoutHover = ComposeColor(0xFF000000)

        /** color/background/knockout-translucent */
        val backgroundKnockoutTranslucent = ComposeColor(0xCC000000)

        /** color/background/selected */
        val backgroundSelected: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFE2B85C) else ComposeColor(0xFFFCEFC0)

        /** color/background/subtle */
        val backgroundSubtle: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF7F7F7)

        /** color/background/subtle-hover */
        val backgroundSubtleHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFFD9D9D9)

        /** color/background/utility/error */
        val backgroundUtilityError: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF390E0E) else ComposeColor(0xFFFCEAEF)

        /** color/background/utility/error-knockout */
        val backgroundUtilityErrorKnockout = ComposeColor(0xFFB82F30)

        /** color/background/utility/info */
        val backgroundUtilityInfo: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF15193F) else ComposeColor(0xFFECEEFC)

        /** color/background/utility/info-knockout */
        val backgroundUtilityInfoKnockout = ComposeColor(0xFF4555D3)

        /** color/background/utility/success */
        val backgroundUtilitySuccess: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF03211A) else ComposeColor(0xFFDCF3EE)

        /** color/background/utility/success-knockout */
        val backgroundUtilitySuccessKnockout = ComposeColor(0xFF0B7058)

        /** color/background/utility/warning */
        val backgroundUtilityWarning: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF2C1900) else ComposeColor(0xFFF9EFBB)

        /** color/background/utility/warning-knockout */
        val backgroundUtilityWarningKnockout = ComposeColor(0xFF8A5801)

        /** color/border/brand */
        val borderBrand: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** color/border/brand-hover */
        val borderBrandHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** color/border/default */
        val borderDefault = ComposeColor(0xFF6F7078)

        /** color/border/disabled */
        val borderDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFF6F7078)

        /** color/border/focus */
        val borderFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF002436) else ComposeColor(0xFF003E4C)

        /** color/border/hover */
        val borderHover = ComposeColor(0xFFEDCF83)

        /** color/border/knockout */
        val borderKnockout = ComposeColor(0xCCFFFFFF)

        /** color/border/knockout-hover */
        val borderKnockoutHover = ComposeColor(0xFFFFFFFF)

        /** color/border/selected */
        val borderSelected: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF6E09E) else ComposeColor(0xFFE2B85C)

        /** color/border/subtle */
        val borderSubtle: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFFC5C6C9)

        /** color/border/subtle-hover */
        val borderSubtleHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF6F7078) else ComposeColor(0xFF8C8F9B)

        /** color/border/utility/error */
        val borderUtilityError: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFDD7C88) else ComposeColor(0xFF8D2121)

        /** color/border/utility/info */
        val borderUtilityInfo: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF8792EA) else ComposeColor(0xFF34409E)

        /** color/border/utility/success */
        val borderUtilitySuccess: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF11AD86) else ComposeColor(0xFF085442)

        /** color/border/utility/warning */
        val borderUtilityWarning: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFDBB305) else ComposeColor(0xFF6D3F00)

        /** color/brand/default */
        val brandDefault = ComposeColor(0xFF003E4C)

        /** color/brand/hover */
        val brandHover = ComposeColor(0xFF002436)

        /** color/content/brand */
        val contentBrand: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** color/content/brand-hover */
        val contentBrandHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** color/content/brand-knockout */
        val contentBrandKnockout = ComposeColor(0xFFF3F4F4)

        /** color/content/default */
        val contentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** color/content/disabled */
        val contentDisabled = ComposeColor(0xFF61646B)

        /** color/content/emphasized */
        val contentEmphasized: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** color/content/eyebrow */
        val contentEyebrow: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** color/content/eyebrow-knockout */
        val contentEyebrowKnockout = ComposeColor(0xFFF3F4F4)

        /** color/content/headline */
        val contentHeadline: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** color/content/headline-brand */
        val contentHeadlineBrand: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** color/content/headline-knockout */
        val contentHeadlineKnockout = ComposeColor(0xFFF3F4F4)

        /** color/content/knockout */
        val contentKnockout = ComposeColor(0xFFF3F4F4)

        /** color/content/link */
        val contentLink: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** color/content/link-hover */
        val contentLinkHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)

        /** color/content/subtitle */
        val contentSubtitle: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** color/content/subtitle-knockout */
        val contentSubtitleKnockout = ComposeColor(0xFFF3F4F4)

        /** color/content/subtle */
        val contentSubtle: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF8C8F9B) else ComposeColor(0xFF6F7078)

        /** color/content/utility/error */
        val contentUtilityError: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFA2B2) else ComposeColor(0xFFB82F30)

        /** color/content/utility/error-knockout */
        val contentUtilityErrorKnockout = ComposeColor(0xFFF3F4F4)

        /** color/content/utility/info */
        val contentUtilityInfo: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFABB3F0) else ComposeColor(0xFF4555D3)

        /** color/content/utility/info-knockout */
        val contentUtilityInfoKnockout = ComposeColor(0xFFF3F4F4)

        /** color/content/utility/success */
        val contentUtilitySuccess: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF5DC9AF) else ComposeColor(0xFF0B7058)

        /** color/content/utility/success-knockout */
        val contentUtilitySuccessKnockout = ComposeColor(0xFFF3F4F4)

        /** color/content/utility/warning */
        val contentUtilityWarning: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFD242) else ComposeColor(0xFF8A5801)

        /** color/content/utility/warning-knockout */
        val contentUtilityWarningKnockout = ComposeColor(0xFFF3F4F4)

        /** color/elevation/shadow */
        val elevationShadow: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xCC000000) else ComposeColor(0x66000000)
    }

    object Elevation {
        /** elevation/lg/blur */
        val lgBlur = 48.dp

        /** elevation/lg/color */
        val lgColor: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xCC000000) else ComposeColor(0x66000000)

        /** elevation/lg/spread */
        val lgSpread = 0.dp

        /** elevation/lg/x */
        val lgX = 0.dp

        /** elevation/lg/y */
        val lgY = 24.dp

        /** elevation/md/blur */
        val mdBlur = 32.dp

        /** elevation/md/color */
        val mdColor: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xCC000000) else ComposeColor(0x66000000)

        /** elevation/md/spread */
        val mdSpread = 0.dp

        /** elevation/md/x */
        val mdX = 0.dp

        /** elevation/md/y */
        val mdY = 16.dp

        /** elevation/sm/blur */
        val smBlur = 16.dp

        /** elevation/sm/color */
        val smColor: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xCC000000) else ComposeColor(0x66000000)

        /** elevation/sm/spread */
        val smSpread = 0.dp

        /** elevation/sm/x */
        val smX = 0.dp

        /** elevation/sm/y */
        val smY = 8.dp

        /** elevation/surface/blur */
        val surfaceBlur = 2.dp

        /** elevation/surface/color */
        val surfaceColor: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xCC000000) else ComposeColor(0x66000000)

        /** elevation/surface/spread */
        val surfaceSpread = 0.dp

        /** elevation/surface/x */
        val surfaceX = 0.dp

        /** elevation/surface/y */
        val surfaceY = 1.dp

        /** elevation/xlg/blur */
        val xlgBlur = 96.dp

        /** elevation/xlg/color */
        val xlgColor: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xCC000000) else ComposeColor(0x66000000)

        /** elevation/xlg/spread */
        val xlgSpread = 0.dp

        /** elevation/xlg/x */
        val xlgX = 0.dp

        /** elevation/xlg/y */
        val xlgY = 48.dp

        /** elevation/xsm/blur */
        val xsmBlur = 8.dp

        /** elevation/xsm/color */
        val xsmColor: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xCC000000) else ComposeColor(0x66000000)

        /** elevation/xsm/spread */
        val xsmSpread = 0.dp

        /** elevation/xsm/x */
        val xsmX = 0.dp

        /** elevation/xsm/y */
        val xsmY = 4.dp

        /** elevation/xxsm/blur */
        val xxsmBlur = 4.dp

        /** elevation/xxsm/color */
        val xxsmColor: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xCC000000) else ComposeColor(0x66000000)

        /** elevation/xxsm/spread */
        val xxsmSpread = 0.dp

        /** elevation/xxsm/x */
        val xxsmX = 0.dp

        /** elevation/xxsm/y */
        val xxsmY = 2.dp
    }

    object Field {
        /** field/border/radius/default */
        val borderRadiusDefault = 4.dp

        /** field/border/radius/read-only */
        val borderRadiusReadOnly = 0.dp

        /** field/border/radius/search */
        val borderRadiusSearch = 9999.dp

        /** field/border/width/default */
        val borderWidthDefault = 1.dp

        /** field/color/background/active */
        val colorBackgroundActive: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** field/color/background/default */
        val colorBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** field/color/background/disabled */
        val colorBackgroundDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF161925) else ComposeColor(0xFFF7F7F7)

        /** field/color/background/focus */
        val colorBackgroundFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** field/color/background/hover */
        val colorBackgroundHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** field/color/background/selected */
        val colorBackgroundSelected: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFE2B85C) else ComposeColor(0xFFFCEFC0)

        /** field/color/border/default */
        val colorBorderDefault = ComposeColor(0xFF6F7078)

        /** field/color/border/disabled */
        val colorBorderDisabled: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFF6F7078)

        /** field/color/border/error */
        val colorBorderError: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFDD7C88) else ComposeColor(0xFF8D2121)

        /** field/color/border/focus */
        val colorBorderFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF002436) else ComposeColor(0xFF003E4C)

        /** field/color/border/hover */
        val colorBorderHover = ComposeColor(0xFFEDCF83)

        /** field/color/border/selected */
        val colorBorderSelected: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF6E09E) else ComposeColor(0xFFE2B85C)

        /** field/color/border/success */
        val colorBorderSuccess: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF11AD86) else ComposeColor(0xFF085442)

        /** field/color/content/default */
        val colorContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF8C8F9B) else ComposeColor(0xFF6F7078)

        /** field/color/content/disabled */
        val colorContentDisabled = ComposeColor(0xFF61646B)

        /** field/color/content/error */
        val colorContentError: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFEFA2B2) else ComposeColor(0xFFB82F30)

        /** field/color/content/focus */
        val colorContentFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** field/color/content/hover */
        val colorContentHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** field/color/content/label */
        val colorContentLabel: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** field/color/content/selected */
        val colorContentSelected: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** field/color/content/success */
        val colorContentSuccess: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF5DC9AF) else ComposeColor(0xFF0B7058)

        /** field/focus-ring/inner-shadow/blur */
        val focusRingInnerShadowBlur = 0.dp

        /** field/focus-ring/inner-shadow/inner-shadow */
        val focusRingInnerShadowInnerShadow: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** field/focus-ring/inner-shadow/spread */
        val focusRingInnerShadowSpread = 2.dp

        /** field/focus-ring/inner-shadow/x */
        val focusRingInnerShadowX = 0.dp

        /** field/focus-ring/inner-shadow/y */
        val focusRingInnerShadowY = 0.dp

        /** field/focus-ring/outer-shadow/blur */
        val focusRingOuterShadowBlur = 0.dp

        /** field/focus-ring/outer-shadow/outer-shadow */
        val focusRingOuterShadowOuterShadow: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF002436) else ComposeColor(0xFF003E4C)

        /** field/focus-ring/outer-shadow/spread */
        val focusRingOuterShadowSpread = 4.dp

        /** field/focus-ring/outer-shadow/x */
        val focusRingOuterShadowX = 0.dp

        /** field/focus-ring/outer-shadow/y */
        val focusRingOuterShadowY = 0.dp

        /** field/spacing/gap */
        val spacingGap = 8.dp

        /** field/spacing/min-height */
        val spacingMinHeight = 48.dp

        /** field/spacing/padding-x */
        val spacingPaddingX = 16.dp

        /** field/spacing/padding-y */
        val spacingPaddingY = 8.dp

        /** field/typography/font-size */
        val typographyFontSize = 16.sp

        /** field/typography/font-weight */
        val typographyFontWeight = FontWeight(500)

        /** field/typography/letter-spacing */
        val typographyLetterSpacing = 0.sp

        /** field/typography/line-height */
        val typographyLineHeight = 24.sp

        /** field/typography/text-transform */
        const val typographyTextTransform = "none"
    }

    object Hyperlink {
        /** hyperlink/color/default */
        val colorDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF248793) else ComposeColor(0xFF003E4C)

        /** hyperlink/color/hover */
        val colorHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF50C5C9) else ComposeColor(0xFF002436)
    }

    object Navbar {
        /** navbar/border/width/default */
        val borderWidthDefault = 1.dp

        /** navbar/color/background/default */
        val colorBackgroundDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF0D0F16) else ComposeColor(0xFFFFFFFF)

        /** navbar/color/border/color/default */
        val colorBorderColorDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFF42454E) else ComposeColor(0xFFC5C6C9)

        /** navbar/color/border/width/default */
        val colorBorderWidthDefault = 1.dp

        /** navbar/color/content/active */
        val colorContentActive: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** navbar/color/content/default */
        val colorContentDefault: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFC5C6C9) else ComposeColor(0xFF42454E)

        /** navbar/color/content/disabled */
        val colorContentDisabled = ComposeColor(0xFF61646B)

        /** navbar/color/content/focus */
        val colorContentFocus: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** navbar/color/content/hover */
        val colorContentHover: ComposeColor
            @Composable @ReadOnlyComposable
            get() = if (isSoftwareDarkTheme()) ComposeColor(0xFFF3F4F4) else ComposeColor(0xFF0D0F16)

        /** navbar/spacing/nav-links/gap */
        val spacingNavLinksGap = 48.dp

        /** navbar/spacing/nav-links/mobile/padding-y */
        val spacingNavLinksMobilePaddingY = 48.dp

        /** navbar/spacing/padding-x */
        val spacingPaddingX = 24.dp

        /** navbar/spacing/padding-y */
        val spacingPaddingY = 16.dp
    }

    object Section {
        /** section/spacing/gap */
        val spacingGap = 24.dp

        /** section/spacing/padding-x */
        val spacingPaddingX = 48.dp

        /** section/spacing/padding-y */
        val spacingPaddingY = 48.dp
    }

    object Spacing {
        /** spacing/0 */
        val _0 = 0.dp

        /** spacing/12 */
        val _12 = 12.dp

        /** spacing/128 */
        val _128 = 128.dp

        /** spacing/16 */
        val _16 = 16.dp

        /** spacing/2 */
        val _2 = 2.dp

        /** spacing/24 */
        val _24 = 24.dp

        /** spacing/32 */
        val _32 = 32.dp

        /** spacing/4 */
        val _4 = 4.dp

        /** spacing/40 */
        val _40 = 40.dp

        /** spacing/48 */
        val _48 = 48.dp

        /** spacing/64 */
        val _64 = 64.dp

        /** spacing/8 */
        val _8 = 8.dp

        /** spacing/80 */
        val _80 = 80.dp

        /** spacing/96 */
        val _96 = 96.dp

        /** spacing/gap/lg */
        val gapLg = 24.dp

        /** spacing/gap/md */
        val gapMd = 16.dp

        /** spacing/gap/none */
        val gapNone = 0.dp

        /** spacing/gap/sm */
        val gapSm = 8.dp

        /** spacing/gap/xlg */
        val gapXlg = 48.dp

        /** spacing/gap/xsm */
        val gapXsm = 4.dp

        /** spacing/gap/xxsm */
        val gapXxsm = 2.dp

        /** spacing/padding/lg */
        val paddingLg = 24.dp

        /** spacing/padding/md */
        val paddingMd = 16.dp

        /** spacing/padding/none */
        val paddingNone = 0.dp

        /** spacing/padding/sm */
        val paddingSm = 8.dp

        /** spacing/padding/xlg */
        val paddingXlg = 48.dp

        /** spacing/padding/xsm */
        val paddingXsm = 4.dp

        /** spacing/padding/xxsm */
        val paddingXxsm = 2.dp
    }

    object Typography {
        /** typography/body-default/font-size */
        val bodyDefaultFontSize = 16.sp

        /** typography/body-default/font-weight */
        val bodyDefaultFontWeight = FontWeight(400)

        /** typography/body-default/letter-spacing */
        val bodyDefaultLetterSpacing = 0.sp

        /** typography/body-default/line-height */
        val bodyDefaultLineHeight = 24.sp

        /** typography/body-default/text-transform */
        const val bodyDefaultTextTransform = "none"

        /** typography/body-emphasized/font-size */
        val bodyEmphasizedFontSize = 16.sp

        /** typography/body-emphasized/font-weight */
        val bodyEmphasizedFontWeight = FontWeight(600)

        /** typography/body-emphasized/letter-spacing */
        val bodyEmphasizedLetterSpacing = 0.sp

        /** typography/body-emphasized/line-height */
        val bodyEmphasizedLineHeight = 24.sp

        /** typography/body-emphasized/text-transform */
        const val bodyEmphasizedTextTransform = "none"

        /** typography/body-lg/font-size */
        val bodyLgFontSize = 20.sp

        /** typography/body-lg/font-weight */
        val bodyLgFontWeight = FontWeight(500)

        /** typography/body-lg/letter-spacing */
        val bodyLgLetterSpacing = 0.sp

        /** typography/body-lg/line-height */
        val bodyLgLineHeight = 28.sp

        /** typography/body-lg/text-transform */
        const val bodyLgTextTransform = "none"

        /** typography/body-sm/font-size */
        val bodySmFontSize = 14.sp

        /** typography/body-sm/font-weight */
        val bodySmFontWeight = FontWeight(400)

        /** typography/body-sm/letter-spacing */
        val bodySmLetterSpacing = 0.sp

        /** typography/body-sm/line-height */
        val bodySmLineHeight = 20.sp

        /** typography/body-sm/text-transform */
        const val bodySmTextTransform = "none"

        /** typography/display-default-mobile/font-size */
        val displayDefaultMobileFontSize = 48.sp

        /** typography/display-default-mobile/font-weight */
        val displayDefaultMobileFontWeight = FontWeight(900)

        /** typography/display-default-mobile/letter-spacing */
        val displayDefaultMobileLetterSpacing = (-1.5).sp

        /** typography/display-default-mobile/line-height */
        val displayDefaultMobileLineHeight = 56.sp

        /** typography/display-default-mobile/text-transform */
        const val displayDefaultMobileTextTransform = "none"

        /** typography/display-default/font-size */
        val displayDefaultFontSize = 72.sp

        /** typography/display-default/font-weight */
        val displayDefaultFontWeight = FontWeight(900)

        /** typography/display-default/letter-spacing */
        val displayDefaultLetterSpacing = (-0.5).sp

        /** typography/display-default/line-height */
        val displayDefaultLineHeight = 80.sp

        /** typography/display-default/text-transform */
        const val displayDefaultTextTransform = "none"

        /** typography/display-sm-mobile/font-size */
        val displaySmMobileFontSize = 32.sp

        /** typography/display-sm-mobile/font-weight */
        val displaySmMobileFontWeight = FontWeight(700)

        /** typography/display-sm-mobile/letter-spacing */
        val displaySmMobileLetterSpacing = (-1).sp

        /** typography/display-sm-mobile/line-height */
        val displaySmMobileLineHeight = 40.sp

        /** typography/display-sm-mobile/text-transform */
        const val displaySmMobileTextTransform = "none"

        /** typography/display-sm/font-size */
        val displaySmFontSize = 40.sp

        /** typography/display-sm/font-weight */
        val displaySmFontWeight = FontWeight(700)

        /** typography/display-sm/letter-spacing */
        val displaySmLetterSpacing = (-1.5).sp

        /** typography/display-sm/line-height */
        val displaySmLineHeight = 48.sp

        /** typography/display-sm/text-transform */
        const val displaySmTextTransform = "none"

        /** typography/font-size/104 */
        val fontSize104 = 104.sp

        /** typography/font-size/12 */
        val fontSize12 = 12.sp

        /** typography/font-size/14 */
        val fontSize14 = 14.sp

        /** typography/font-size/16 */
        val fontSize16 = 16.sp

        /** typography/font-size/18 */
        val fontSize18 = 18.sp

        /** typography/font-size/20 */
        val fontSize20 = 20.sp

        /** typography/font-size/24 */
        val fontSize24 = 24.sp

        /** typography/font-size/28 */
        val fontSize28 = 28.sp

        /** typography/font-size/32 */
        val fontSize32 = 32.sp

        /** typography/font-size/40 */
        val fontSize40 = 40.sp

        /** typography/font-size/48 */
        val fontSize48 = 48.sp

        /** typography/font-size/56 */
        val fontSize56 = 56.sp

        /** typography/font-size/64 */
        val fontSize64 = 64.sp

        /** typography/font-size/72 */
        val fontSize72 = 72.sp

        /** typography/font-size/80 */
        val fontSize80 = 80.sp

        /** typography/font-size/88 */
        val fontSize88 = 88.sp

        /** typography/font-size/96 */
        val fontSize96 = 96.sp

        /** typography/font-weight/400 */
        val fontWeight400 = FontWeight(400)

        /** typography/font-weight/500 */
        val fontWeight500 = FontWeight(500)

        /** typography/font-weight/600 */
        val fontWeight600 = FontWeight(600)

        /** typography/font-weight/700 */
        val fontWeight700 = FontWeight(700)

        /** typography/font-weight/800 */
        val fontWeight800 = FontWeight(800)

        /** typography/font-weight/900 */
        val fontWeight900 = FontWeight(900)

        /** typography/font-weight/bold */
        const val fontWeightBold = "Bold"

        /** typography/font-weight/extrabold */
        const val fontWeightExtrabold = "Extra Bold"

        /** typography/font-weight/medium */
        const val fontWeightMedium = "Medium"

        /** typography/font-weight/regular */
        const val fontWeightRegular = "Regular"

        /** typography/font-weight/semi */
        const val fontWeightSemi = "Semi Bold"

        /** typography/headline-default-mobile/font-size */
        val headlineDefaultMobileFontSize = 32.sp

        /** typography/headline-default-mobile/font-weight */
        val headlineDefaultMobileFontWeight = FontWeight(700)

        /** typography/headline-default-mobile/letter-spacing */
        val headlineDefaultMobileLetterSpacing = 0.5.sp

        /** typography/headline-default-mobile/line-height */
        val headlineDefaultMobileLineHeight = 40.sp

        /** typography/headline-default-mobile/text-transform */
        const val headlineDefaultMobileTextTransform = "none"

        /** typography/headline-default/font-size */
        val headlineDefaultFontSize = 40.sp

        /** typography/headline-default/font-weight */
        val headlineDefaultFontWeight = FontWeight(700)

        /** typography/headline-default/letter-spacing */
        val headlineDefaultLetterSpacing = 0.5.sp

        /** typography/headline-default/line-height */
        val headlineDefaultLineHeight = 48.sp

        /** typography/headline-default/text-transform */
        const val headlineDefaultTextTransform = "none"

        /** typography/headline-lg-mobile/font-size */
        val headlineLgMobileFontSize = 40.sp

        /** typography/headline-lg-mobile/font-weight */
        val headlineLgMobileFontWeight = FontWeight(700)

        /** typography/headline-lg-mobile/letter-spacing */
        val headlineLgMobileLetterSpacing = 0.5.sp

        /** typography/headline-lg-mobile/line-height */
        val headlineLgMobileLineHeight = 48.sp

        /** typography/headline-lg-mobile/text-transform */
        const val headlineLgMobileTextTransform = "none"

        /** typography/headline-lg/font-size */
        val headlineLgFontSize = 48.sp

        /** typography/headline-lg/font-weight */
        val headlineLgFontWeight = FontWeight(700)

        /** typography/headline-lg/letter-spacing */
        val headlineLgLetterSpacing = 0.5.sp

        /** typography/headline-lg/line-height */
        val headlineLgLineHeight = 56.sp

        /** typography/headline-lg/text-transform */
        const val headlineLgTextTransform = "none"

        /** typography/headline-sm-mobile/font-size */
        val headlineSmMobileFontSize = 28.sp

        /** typography/headline-sm-mobile/font-weight */
        val headlineSmMobileFontWeight = FontWeight(700)

        /** typography/headline-sm-mobile/letter-spacing */
        val headlineSmMobileLetterSpacing = 0.5.sp

        /** typography/headline-sm-mobile/line-height */
        val headlineSmMobileLineHeight = 36.sp

        /** typography/headline-sm-mobile/text-transform */
        const val headlineSmMobileTextTransform = "none"

        /** typography/headline-sm/font-size */
        val headlineSmFontSize = 32.sp

        /** typography/headline-sm/font-weight */
        val headlineSmFontWeight = FontWeight(700)

        /** typography/headline-sm/letter-spacing */
        val headlineSmLetterSpacing = 0.5.sp

        /** typography/headline-sm/line-height */
        val headlineSmLineHeight = 40.sp

        /** typography/headline-sm/text-transform */
        const val headlineSmTextTransform = "none"

        /** typography/label-default/font-size */
        val labelDefaultFontSize = 16.sp

        /** typography/label-default/font-weight */
        val labelDefaultFontWeight = FontWeight(500)

        /** typography/label-default/letter-spacing */
        val labelDefaultLetterSpacing = 0.sp

        /** typography/label-default/line-height */
        val labelDefaultLineHeight = 24.sp

        /** typography/label-default/text-transform */
        const val labelDefaultTextTransform = "none"

        /** typography/label-lg/font-size */
        val labelLgFontSize = 20.sp

        /** typography/label-lg/font-weight */
        val labelLgFontWeight = FontWeight(600)

        /** typography/label-lg/letter-spacing */
        val labelLgLetterSpacing = 0.sp

        /** typography/label-lg/line-height */
        val labelLgLineHeight = 28.sp

        /** typography/label-lg/text-transform */
        const val labelLgTextTransform = "none"

        /** typography/label-sm/font-size */
        val labelSmFontSize = 14.sp

        /** typography/label-sm/font-weight */
        val labelSmFontWeight = FontWeight(500)

        /** typography/label-sm/letter-spacing */
        val labelSmLetterSpacing = 0.sp

        /** typography/label-sm/line-height */
        val labelSmLineHeight = 16.sp

        /** typography/label-sm/text-transform */
        const val labelSmTextTransform = "none"

        /** typography/letter-spacing/0 */
        val letterSpacing0 = 0.sp

        /** typography/letter-spacing/1 */
        val letterSpacing1 = 1.sp

        /** typography/letter-spacing/1-half */
        val letterSpacing1Half = 1.5.sp

        /** typography/letter-spacing/2 */
        val letterSpacing2 = 2.sp

        /** typography/letter-spacing/half */
        val letterSpacingHalf = 0.5.sp

        /** typography/letter-spacing/minus-1 */
        val letterSpacingMinus1 = (-1).sp

        /** typography/letter-spacing/minus-1-half */
        val letterSpacingMinus1Half = (-1.5).sp

        /** typography/letter-spacing/minus-2 */
        val letterSpacingMinus2 = (-2).sp

        /** typography/letter-spacing/minus-half */
        val letterSpacingMinusHalf = (-0.5).sp

        /** typography/line-height/104 */
        val lineHeight104 = 104.sp

        /** typography/line-height/112 */
        val lineHeight112 = 112.sp

        /** typography/line-height/16 */
        val lineHeight16 = 16.sp

        /** typography/line-height/20 */
        val lineHeight20 = 20.sp

        /** typography/line-height/24 */
        val lineHeight24 = 24.sp

        /** typography/line-height/28 */
        val lineHeight28 = 28.sp

        /** typography/line-height/32 */
        val lineHeight32 = 32.sp

        /** typography/line-height/36 */
        val lineHeight36 = 36.sp

        /** typography/line-height/40 */
        val lineHeight40 = 40.sp

        /** typography/line-height/48 */
        val lineHeight48 = 48.sp

        /** typography/line-height/56 */
        val lineHeight56 = 56.sp

        /** typography/line-height/64 */
        val lineHeight64 = 64.sp

        /** typography/line-height/72 */
        val lineHeight72 = 72.sp

        /** typography/line-height/80 */
        val lineHeight80 = 80.sp

        /** typography/line-height/88 */
        val lineHeight88 = 88.sp

        /** typography/line-height/96 */
        val lineHeight96 = 96.sp

        /** typography/meta-default/font-size */
        val metaDefaultFontSize = 14.sp

        /** typography/meta-default/font-weight */
        val metaDefaultFontWeight = FontWeight(400)

        /** typography/meta-default/letter-spacing */
        val metaDefaultLetterSpacing = 0.sp

        /** typography/meta-default/line-height */
        val metaDefaultLineHeight = 20.sp

        /** typography/meta-default/text-transform */
        const val metaDefaultTextTransform = "none"

        /** typography/meta-sm/font-size */
        val metaSmFontSize = 12.sp

        /** typography/meta-sm/font-weight */
        val metaSmFontWeight = FontWeight(400)

        /** typography/meta-sm/letter-spacing */
        val metaSmLetterSpacing = 0.sp

        /** typography/meta-sm/line-height */
        val metaSmLineHeight = 16.sp

        /** typography/meta-sm/text-transform */
        const val metaSmTextTransform = "none"

        /** typography/text-transform/capitalize */
        const val textTransformCapitalize = "capitalize"

        /** typography/text-transform/lowercase */
        const val textTransformLowercase = "lowercase"

        /** typography/text-transform/none */
        const val textTransformNone = "none"

        /** typography/text-transform/uppercase */
        const val textTransformUppercase = "uppercase"

        /** typography/title-default/font-size */
        val titleDefaultFontSize = 28.sp

        /** typography/title-default/font-weight */
        val titleDefaultFontWeight = FontWeight(700)

        /** typography/title-default/letter-spacing */
        val titleDefaultLetterSpacing = (-0.5).sp

        /** typography/title-default/line-height */
        val titleDefaultLineHeight = 36.sp

        /** typography/title-default/text-transform */
        const val titleDefaultTextTransform = "none"

        /** typography/title-lg-mobile/font-size */
        val titleLgMobileFontSize = 28.sp

        /** typography/title-lg-mobile/font-weight */
        val titleLgMobileFontWeight = FontWeight(700)

        /** typography/title-lg-mobile/letter-spacing */
        val titleLgMobileLetterSpacing = (-0.5).sp

        /** typography/title-lg-mobile/line-height */
        val titleLgMobileLineHeight = 36.sp

        /** typography/title-lg-mobile/text-transform */
        const val titleLgMobileTextTransform = "none"

        /** typography/title-lg/font-size */
        val titleLgFontSize = 32.sp

        /** typography/title-lg/font-weight */
        val titleLgFontWeight = FontWeight(700)

        /** typography/title-lg/letter-spacing */
        val titleLgLetterSpacing = (-1).sp

        /** typography/title-lg/line-height */
        val titleLgLineHeight = 40.sp

        /** typography/title-lg/text-transform */
        const val titleLgTextTransform = "none"

        /** typography/title-sm/font-size */
        val titleSmFontSize = 24.sp

        /** typography/title-sm/font-weight */
        val titleSmFontWeight = FontWeight(500)

        /** typography/title-sm/letter-spacing */
        val titleSmLetterSpacing = (-0.5).sp

        /** typography/title-sm/line-height */
        val titleSmLineHeight = 32.sp

        /** typography/title-sm/text-transform */
        const val titleSmTextTransform = "none"
    }

    /** Grid values for one layout size. Pick one with [Grid.forWidth]. */
    @Immutable
    data class GridMode(
        val columns: Int,
        val containerGutter: Dp,
        val defaultWidth: Dp,
        val maxWidth: Dp,
        val minWidth: Dp,
        val sectionGap: Dp,
        val sectionPadding: Dp,
        val viewport: String,
    )

    object Grid {
        val small = GridMode(
            columns = 2,
            containerGutter = 16.dp,
            defaultWidth = 375.dp,
            maxWidth = 560.dp,
            minWidth = 320.dp,
            sectionGap = 16.dp,
            sectionPadding = 16.dp,
            viewport = "small",
        )
        val medium = GridMode(
            columns = 8,
            containerGutter = 16.dp,
            defaultWidth = 768.dp,
            maxWidth = 960.dp,
            minWidth = 560.dp,
            sectionGap = 24.dp,
            sectionPadding = 24.dp,
            viewport = "medium",
        )
        val large = GridMode(
            columns = 12,
            containerGutter = 24.dp,
            defaultWidth = 1200.dp,
            maxWidth = 1600.dp,
            minWidth = 960.dp,
            sectionGap = 48.dp,
            sectionPadding = 48.dp,
            viewport = "large",
        )

        /** Largest mode whose minimum width fits. Use the window width, not the screen. */
        fun forWidth(width: Dp): GridMode =
            listOf(large, medium, small).firstOrNull { width >= it.minWidth } ?: small
    }
}
